### ISSUE TITLE
Add Rack middleware to downcase all request URLs

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1007]
There are a couple places where we look up something by it's `slug` which is all lowercase.  But incoming requests can be to any combination of cased URLs. Sometimes this produces unexpected results.

- http://crimethinc.com/tags/Nicaragua => tag not found, redirect to home
- http://crimethinc.com/tags/nicaragua => works as expected

(Handling the case of slugs for tags, etc is a separate issue.)

To add a bit of [resilience to what we accept](https://en.wikipedia.org/wiki/Robustness_principle), let's add a Rack middleware that transforms all requested URLs and paths to lowercase before handing them off to redirects or to the app.

***

See any of these files for the basic structure of a Rack middleware:

https://github.com/crimethinc/website/tree/master/app/middlewares/rack

**Comment by natestemen** [comment]
http://crimethinc.com/tags/Nicaragua is now redirecting to http://crimethinc.com/tags/nicaragua for me. I think this has been fixed?

**Comment by veganstraightedge** [comment]
@natestemen I'm super Safari on macOS and it did not redirect for me.

Maybe some browsers do it themselves?

Which browser/version/os id you try this on?

Also, hi! Thanks for dropping in.

**Comment by veganstraightedge** [comment]
@natestemen Nevermind. I mis-saw what my browser was doing. 

I think you're right that this is done did. I'll close it now. Thanks for pointing that out.

Is there anything else that you'd like to work on instead? If so, let us know if we can help you get up and going on it.

**Comment by natestemen** [comment]
I'll take a look around later and see if anything looks good for me. Feel free to point me towards anything that would be helpful in the short term and would be a good intro.

**Comment by veganstraightedge** [comment]
Will do.

Are you looking for more Rails / backend?
CSS / frontend?
DevOps?
