### ISSUE TITLE
Upgrade to Ruby 2.6 and Bundler 2.0

### ISSUE THREAD

**Issue by lazzarello** [crimethinc/website#1015]
`.ruby-version` is at 2.5.3 and bundler was updated a few weeks prior to this writing to version 2.0, which is not compatible with ruby < 2.6. A workaround is to install a lower version of bundler by passing a parameter like `gem install bundler -v 1.17.3`. The long term solution is to upgrade Ruby and Bundler.

**Comment by veganstraightedge** [comment]
This is contingent on Heroku shipping Bundler 2 support (without a special build pack).

https://bundler.io/blog/2019/01/03/announcing-bundler-2.html

**Comment by astronaut-wannabe** [comment]
@veganstraightedge I *think* this is done:
- https://github.com/crimethinc/website/pull/1160
- https://github.com/crimethinc/website/pull/1141

**Comment by veganstraightedge** [comment]
Yep!
