### ISSUE TITLE
Tune pg performance

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#103]
https://blog.heroku.com/postgres-essentials

**Comment by kmanzana** [comment]
Are there any particular queries or page loads that are known to be issues?  Is there any app performance monitoring?  Trying to figure out if this is fixing a bad user experience or should be done for some other reason.

**Comment by veganstraightedge** [comment]
Nothing in particular. I just know that I've been naive about all of the acrove record code that I've written. I expect that there are places that can be tuned by some common sense improvements.
