### ISSUE TITLE
[TCE] Replace icon font with SVG icons

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1060]
# [crimethinc.com/tce](https://crimethinc.com/tce)

<img width="490" alt="screen shot 2019-03-05 at 9 08 56 pm" src="https://user-images.githubusercontent.com/4361/53857391-f631b400-3f8a-11e9-8eee-29a16e1d7ca4.png">

Icon font is used in the header nav. Maybe elsewhere too?

https://github.com/crimethinc/website/blob/1078fb874181cf77eeead05c4c84435ff48ab677/app/views/layouts/to_change_everything.html.erb#L69
https://github.com/crimethinc/website/blob/1078fb874181cf77eeead05c4c84435ff48ab677/app/views/layouts/to_change_everything.html.erb#L79
https://github.com/crimethinc/website/blob/1078fb874181cf77eeead05c4c84435ff48ab677/app/views/layouts/to_change_everything.html.erb#L89

***

**UPDATE:** all of the icons are now here, as SVGs. 

https://github.com/crimethinc/website/tree/master/app/assets/images/to-change-everything/icons

**Comment by danarel** [comment]
I would suggest replacing those images with Fork Awesome SVGs / fonts.

https://forkaweso.me/Fork-Awesome/icons/

Easier than recreating what's already out there.

**Comment by veganstraightedge** [comment]
Thanks @danarel. Could you help us find the matching SVG icons in that set?

**Comment by IgnazNepumuk** [comment]
[tce_glyphs.tar.gz](https://github.com/crimethinc/website/files/4006153/tce_glyphs.tar.gz)

I have exported all the glyphs to svg and packed it as .tgz

**Comment by veganstraightedge** [comment]
Thanks @IgnazNepumuk! I'll work on adding them to the codebase now. 👍🏻

**Comment by veganstraightedge** [comment]
I added the SVGs to the codebase. 

https://github.com/crimethinc/website/tree/master/app/assets/images/to-change-everything/icons
