### ISSUE TITLE
Find CSSer

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1104]
We're redesigning the site and need a person (or people!) to write the CSS. 🎉

It's a Ruby on Rails app. But even if you don't have any experience with Ruby/Rails, don't worry about it. We can help ramp you up to be able to work on the CSS without know hardly anything about Ruby. 

Interested? Willing? Able? Leave a comment on this issue and we'll be in touch. 🖤🏴

**Comment by GeoffFoley** [comment]
Are we ready with mockups?

**Comment by veganstraightedge** [comment]
Yep. I'm gonna close this since you're gonna be taking on the redesign, @GeoffFoley. Thanks!
