### ISSUE TITLE
Strip HTML tags from title tag

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1170]
https://crimethinc.com/2019/06/11/weve-reprinted-work-and-expect-resistance

<img width="464" alt="Screen Shot 2019-06-11 at 9 42 21 PM" src="https://user-images.githubusercontent.com/4361/59398540-75324780-8d45-11e9-86b3-f966af868b8b.png">

<img width="260" alt="Screen Shot 2019-06-11 at 7 50 24 PM" src="https://user-images.githubusercontent.com/4361/59398541-75324780-8d45-11e9-938d-c0d1fc17a6e4.png">

<img width="1094" alt="Screen Shot 2019-06-12 at 7 09 22 PM" src="https://user-images.githubusercontent.com/4361/59398635-c4787800-8d45-11e9-9093-57aa2240e3f3.png">

<img width="820" alt="Screen Shot 2019-06-12 at 7 09 32 PM" src="https://user-images.githubusercontent.com/4361/59398636-c4787800-8d45-11e9-8d94-3a1be519bba5.png">

https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_tags

**Comment by Jngai** [comment]
I will take care of this.

**Comment by astronaut-wannabe** [comment]
@Jngai thanks for picking this up!

The development cache should only. be 1 second in development, so. aybe something else is going on?

You can toggle the cache on/off by running: 
```sh
bundle exec rails dev:cache
```

**Comment by veganstraightedge** [comment]
@Jngai Thanks for taking on this issue!

@astronaut-wannabe suggestion is good. 👍🏻
If that also doesn't work, then you could comment out the `cache`/`end` lines while you do your development.

Let us know if there's anything else that we can do to help.

**Comment by veganstraightedge** [comment]
<img width="954" alt="markdown bug" src="https://user-images.githubusercontent.com/4361/62902916-ed04fa00-bd15-11e9-82fe-f0b436e536d7.png">

This same bug is also happening on suggested article cards in the footer of articles.

Maybe after you solve your issue's bug, we can abstract whatever solution you come up with into a generalized solution for all titles/subtitles.

**Comment by veganstraightedge** [comment]
Hi @Jngai. 👋🏻 
Just checking in to see how it's going on this issue. 

Any troubles that we can help you with?

**Comment by Jngai** [comment]
@veganstraightedge I went and contributed to another project instead...I remember I was stuck. If I have time I will come back to it and ask you for directions.

**Comment by veganstraightedge** [comment]
Ok. 👍🏻

Would you like to hold onto this issue or set it free for someone else to pick up? Either way is ok.

**Comment by Jngai** [comment]
set it free please

**Comment by veganstraightedge** [comment]
https://github.com/crimethinc/website/pull/1337
