### ISSUE TITLE
UI: support button is over the logo on rtl site version

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#1225]
When the website is in right to left text mode, the support us button is over the crimethinc logo instead of being at the left of the header.

![image](https://user-images.githubusercontent.com/427123/62257052-beac2400-b3d1-11e9-9bfb-732e3b83372a.png)

Probably introduce by #1221

**Comment by veganstraightedge** [comment]
Definitely introduced by #1221. Which was for the [Hebrew translation of the Willem article](https://crimethinc.com/2019/07/14/hebrew-on-willem-van-spronsens-action-against-the-northwest-detention-center-in-tacoma-including-the-full-text-of-his-final-statement)

It was very quick and dirty. 

And if I recall correctly, the support button is absolutely positioned.
