### ISSUE TITLE
Handle JSON requests somehow

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1235]
Sometimes requests show up with: `"Accept": "application/json",`.

What should we do about these?

- redirect them to `html` version?
- check for accepts JSON in middleware or something and return an http status?
- something else

My goal is to keep these kind fo requests out of Bugsnag.

**Comment by astronaut-wannabe** [comment]
maybe just throw a before action in the application_controller

something like
```ruby
def check_for_json_request
  if request.is_a_json_request? #this is not real code, just how i am thinking about it
    render status: :not_acceptable, json: { errors: [{ status: "406", title:  "Content Type Not Acceptable", detail: "Y'all requested JSON, but we don't do that" }] }.to_json
  end
end
```

**Comment by just1602** [comment]
It can even been a middleware to avoid entering controllers.

**Comment by veganstraightedge** [comment]
@just1602 Agreed. This feels like it should be a middleware.
