### ISSUE TITLE
Adding Guard for faster TDD-Cycling

### ISSUE THREAD

**Issue by nerdspar** [crimethinc/website#1252]
Is there any objection to adding Guard for faster cycling?  Seems to help me work quicker, but of course I defer to the group.

**Comment by veganstraightedge** [comment]
https://github.com/crimethinc/website/blob/master/Gemfile#L79

https://github.com/crimethinc/website/blob/master/Guardfile

Feel free to update if it doesn't work in its current state.

**Comment by nerdspar** [comment]
Apologies, totally overlooked this.  Closing
