### ISSUE TITLE
Refactor jquery out of non-admin JS

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1254]
There are only two pages (on the public facing site) that use Javascript:

- https://crimethinc.com/support
- live blog articles, of which there are only three:
  - https://crimethinc.com/live (J20)
  - https://crimethinc.com/airportblockades (airport blockades)
  - https://crimethinc.com/g20live (G20 in Hamburg)

That Javascript (now) only loads on those pages, instead of all pages and all articles.

Let's see if we can cut down the page load of those two pages (and a couple JS dependencies) by refactoring the JS to use browser native Javascript only, no jquery, no other libraries.

- [x] `support.js` https://github.com/crimethinc/website/blob/master/app/assets/javascripts/support.js
- [x] live blog article js (not all actually use jquery)
  - [x] https://github.com/crimethinc/website/blob/master/app/assets/javascripts/base.js
  - [x] https://github.com/crimethinc/website/blob/master/app/assets/javascripts/article_queue.js
  - [x] https://github.com/crimethinc/website/blob/master/app/assets/javascripts/articles.js
  - [x] https://github.com/crimethinc/website/blob/master/app/assets/javascripts/articles_poll.js

***

The [`admin.js`](https://github.com/crimethinc/website/blob/master/app/assets/javascripts/admin.js) site still uses jQuery (in Bootstrap) and that's just fine for now. Also, Bootstrap v5 is dropping jquery too. https://github.com/twbs/bootstrap/pull/23586

[SSfWD js](https://github.com/crimethinc/website/blob/master/app/assets/javascripts/steal-something-from-work-day.js) can also be ignored for now.

**Comment by Andykmcc** [comment]
Hi, i'm happy to take care of this, this evening (pacific time).

**Comment by veganstraightedge** [comment]
Thanks @Andykmcc! 

It also looks like @wbholland (thanks!) already PRed one of the files. 

Maybe you two can coordinate to divide and conquer the work?

**Comment by wbholland** [comment]
Sorry, first time contributing to a repository and didn't think about claiming on here before I began work. I think only 2 other files (support.js and articles_poll.js) need refactoring. @Andykmcc feel free to grab these and even check over my PR if you'd like.

**Comment by Andykmcc** [comment]
no worries @wbholland. i'll take a look at those other two files now and am happy to trade code reviews.

**Comment by veganstraightedge** [comment]
@Andykmcc @wbholland Would y'all mind taking a look at this other JS file?

https://github.com/crimethinc/website/blob/master/app/assets/javascripts/articles_poll.js

**Comment by wbholland** [comment]
Sure, I'll give it a go

**Comment by veganstraightedge** [comment]
Final PR was https://github.com/crimethinc/website/pull/1262 

Great job, everyone!
