### ISSUE TITLE
Duplicate travis-ci config

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#1335]
We have both [database.travis.yml](https://github.com/crimethinc/website/blob/master/config/database.travis.yml) and [database.yml.travis](https://github.com/crimethinc/website/blob/master/config/database.yml.travis). The only difference is the database name. should we keep both of them?

**Comment by veganstraightedge** [comment]
We can delete both. We've away from Travis for CI. We're down to just Heroku and GitHub Actions.
