### ISSUE TITLE
Build URL shortener

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#134]
TODO

**Comment by greggawatt** [comment]
I've never built one before, but seems fun, what are the specs required for this?

**Comment by veganstraightedge** [comment]
Well. You managed to find another issue that can prolly be punted on. Or at least in the way I originally wrote it. o_O

The way I ended up building the `Redirects` covers 80% of our use case. Because we're not doing algorithmic short URLs, say using Base64 encoding on the id or something, it's really just a lookup table.

`/live` goes to `/2017/01/20/j20-live-blog`, for example.

But that's what the `Redirects` already do.

What could be done to improve this though, is to add a `short_path` attribute to `Article`.
And adding a validation to `Article` to make sure that `short_path` is unique:
- in the `redirects` table against the `source_path` column
- amongst other `articles` against the `short_path` column

****

Extra credit, you could create the `Redirect` with:
- `redirect.source_path` set to `article.short_path` and
- `redirect.target_path` set to `article.path`

*** 

Extra extra credit, if an `article` is being `updated` and `short_path` or `path` (by way of changing title/subtitle/slug/published_at) is being changed, before doing the `update`, check to see if there's a `Redirect` with the `article`'s previous `short_path` and `path` values. And if it does exist, either delete it and replace with a new one for the updated `short_path` and `path` values.

Wow. That was a complicated paragraph. Beep me if you need me to clarify that.

**Comment by greggawatt** [comment]
How should the `short_path` be generated?

**Comment by veganstraightedge** [comment]
`rails generate migration add_short_path_to_articles short_path`

**Comment by veganstraightedge** [comment]
Or do you mean the value for `short_path`?

That would be user inputted.

**Comment by greggawatt** [comment]
Yes, if it was user generated, but thanks for the migration 😉

I'll start on this tonight
