### ISSUE TITLE
Add titles to /languages/* pages

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1568]
https://crimethinc.com/languages/bengali

It should have a title tag value like: `বাংলা / Bengali (baanlaa)`

**Comment by just1602** [comment]
Is there something else than the actual title going here?

![image](https://user-images.githubusercontent.com/427123/81850359-dfd79e80-9525-11ea-81ef-f7e1b11db068.png)

**Comment by veganstraightedge** [comment]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/4361/81850615-148b2c00-950d-11ea-99cb-8a0b8c61ed37.png">

Nope! It just needs a decent title. Right now, it's empty / the default site title.

**Comment by just1602** [comment]
Ohhh you mean this title ! Got it !

**Comment by just1602** [comment]
@veganstraightedge call you tell me what would I need to do to make `@title = PageTitle.new title_for(:languages)` to render `Crimethinc. : Languages` instead of `Crimethinc. : index` as `/languages` title?

**Comment by just1602** [comment]
If i use `title_for("Languages")` it works, but I want it to be translatable.. But i don't understand why it didn't work with the symbol since there is a `languages` key in the en locale file?

**Comment by just1602** [comment]
Ok, got it ! :D
