### ISSUE TITLE
Make custom 404, 500 and 422 pages

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#157]
Content: https://github.com/crimethinc/website/issues/176

**Comment by veganstraightedge** [comment]
- [ ] *404* : https://github.com/crimethinc/website/blob/master/public/404.html
- [ ] *500* : https://github.com/crimethinc/website/blob/master/public/500.html

**Comment by veganstraightedge** [comment]
@mousemke Can you take a first pass at this? Those pages have to be completely self sufficient. No SCSS or external CSS. I'll upload the images to S3.

**Comment by veganstraightedge** [comment]
Images:

http://thecloud.crimethinc.com/assets/errors/404.jpg
http://thecloud.crimethinc.com/assets/errors/500.jpg

**Comment by mousemke** [comment]
are we sure having [1mb and 2mb respectively] images on the 404 and 500 pages is appropriate? Seems kind of unnecessary. 

Also, I tried loading the 500 image on 3g and it took 22 seconds.

![http://pics.knoblau.ch/500.jpg_26672000_2017-01-02_20-42-41.png](http://pics.knoblau.ch/500.jpg_26672000_2017-01-02_20-42-41.png)

**Comment by veganstraightedge** [comment]
You can downsize it as necessary. When you get something good, email it to me and I'll reupload.

**Comment by mousemke** [comment]
cool

**Comment by just1602** [comment]
@astronaut-wannabe do you think we should also do a 422 page ?

**Comment by astronaut-wannabe** [comment]
@just1602 not sure. It would be simple enough, but I think that would only ever really happen on `admin` pages, so maybe not needed

**Comment by just1602** [comment]
@astronaut-wannabe, nice that means we can close this issue ! :D

**Comment by veganstraightedge** [comment]
Agreed. We don't need a 422. 

Thanks for doing this one. 👍🏻
