### ISSUE TITLE
Add meta data to tools pages

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1571]
Books, zines, stickers, posters, logos, videos should all have the right meta tags to generate a preview when pasted into Slack, Messages, etc.

Here is a book, not expanding a preview.

![image](https://user-images.githubusercontent.com/4361/80022487-00fe1f80-8491-11ea-8e6e-d8af628fbe0f.png)

See an article page for example meta tags.

For example:
https://crimethinc.com/2020/04/21/whats-worth-dying-for-confronting-the-return-to-business-as-usual

Preview:
<img width="254" alt="Screen Shot 2020-04-22 at 12 03 05 PM" src="https://user-images.githubusercontent.com/4361/80022684-46bae800-8491-11ea-8911-7c8d5ecac430.png">

Meta tags:
<img width="1423" alt="Screen Shot 2020-04-22 at 12 04 28 PM" src="https://user-images.githubusercontent.com/4361/80022798-6eaa4b80-8491-11ea-931a-ecc0b2df8d91.png">

**Comment by astronaut-wannabe** [comment]
i cannot reproduce this. also, it looks like books, zines, and other tools already have social meta tags

**Comment by just1602** [comment]
I just try it myself with older and super recent article, and I cannot reproduce.

I'll close for now.
