### ISSUE TITLE
Migrate auto-prefixer to web packer build process

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1719]
# Autoprefixer Rails was Deprecated

https://github.com/ai/autoprefixer-rails/wiki/Deprecated

> The best option is to migrate to the Node.js frontend build system. Here is a good guide: Part 1, Part 2, Part 3.

Part 1: https://evilmartians.com/chronicles/evil-front-part-1
Part 2: https://evilmartians.com/chronicles/evil-front-part-2
Part 3: https://evilmartians.com/chronicles/evil-front-part-3

***

https://github.com/crimethinc/website/blob/main/app/assets/config/manifest.js

We don't currently have a `package.json` or a node/npm version in our `Brewfile` or dev setup scripts. Seems like we'll have to address all of that to do this. Or maybe not!

**Comment by just1602** [comment]
Bootstrap 5 is gonna be stabilize very soon and it drop a lot of js stuff like jquery. If we're lucky enough, it's gonna also drop autoprefixer, so we could simply migrate the admin to bootstrap 5.

I know it's a lot of job, but if it could avoid us adding js dependencies it'd awesome !

**Comment by veganstraightedge** [comment]
@just1602 That's a very good point. I think that you're right that we should wait until Bootstrap 5. Good idea!

**Comment by just1602** [comment]
We probably have to migrate to bootstrap 5, but we don't care if it use autoprefixer or not since the gem has found a [new maintainer](https://github.com/ai/autoprefixer-rails/issues/184).

**Comment by veganstraightedge** [comment]
🎉
