### ISSUE TITLE
Content for Error pages

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#176]
# 404
## File not found

- [ ] Sub/Title
- [ ] Image
- [ ] Paragraph or two
- [ ] Suggested paths from here (search, /read, etc)

# 500
## Internal App Error (we fucked up)

- [ ] Sub/Title
- [ ] Image
- [ ] Paragraph or two
- [ ] Suggested paths from here (search, /read, etc)

**Comment by biofilo** [comment]
Error 404: File Not Found

http://lapiedradesisifo.com/wp-content/uploads/2015/08/Biblioteca.jpg <http://lapiedradesisifo.com/wp-content/uploads/2015/08/Biblioteca.jpg>
or
http://dorothygebert.com/wp-content/uploads/2014/04/enhanced-buzz-wide-1782-1374872169-42.jpg <http://dorothygebert.com/wp-content/uploads/2014/04/enhanced-buzz-wide-1782-1374872169-42.jpg>

The page you are looking for does not seem to be here. To go hunting for it, [use our sophisticated search engine,](LINK?) or peruse our [reading library.](LINK) To report a problem to us, [DO THIS.]


Error 500: Internal App Error

http://static.travelinglifestyle.net/uploads/2016/04/travel-inspiration.jpeg <http://static.travelinglifestyle.net/uploads/2016/04/travel-inspiration.jpeg>

The page you are looking for does not seem to be here. To go hunting for it, [use our sophisticated search engine,](LINK?) or peruse our [reading library.](LINK) To report a problem to us, [DO THIS.]
