### ISSUE TITLE
Collect all videos for /watch

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#177]
My plan for /watch is to include all the videos from:

- [x] http://www.crimethinc.com/movies (english and spanish)
- [x] https://vimeo.com/crimethinc
- [x] http://www.crimethinc.com/tce

***

If there are others, list them here in the comments, and I'll include them.

**Comment by biofilo** [comment]
http://www.crimethinc.com/blog/2011/11/06/oakland-general-strike-footage/

...and what do we do about all the versions of the TCE video in other languages? Just link to tochangeeverything.com with a note saying they are available there...? Or is the idea that having different language pages for crimethinc.com will cover that?

**Comment by veganstraightedge** [comment]
How many other language TCE videos are there?

**Comment by biofilo** [comment]
Like, a dozen.

**Comment by biofilo** [comment]
And in addition... I think we should probably add the video shorts from the DVD at some point:

http://www.crimethinc.com/tools/dvd.html

**Comment by veganstraightedge** [comment]
Agreed. Do the video files exist somewhere other than the DVDs themselves?

**Comment by biofilo** [comment]
Scott would have them, if anyone…
