### ISSUE TITLE
Strange stretched images at top of features

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#183]
https://crimethinc-staging.herokuapp.com/1900/09/11/border
and 
https://crimethinc-staging.herokuapp.com/1900/09/11/barc
for example.

**Comment by biofilo** [comment]
and https://crimethinc-staging.herokuapp.com/1900/09/11/breaking

**Comment by mousemke** [comment]
css on the image is set to width 100%

**Comment by mousemke** [comment]
i'm still getting into this project, so i cant know the overall scope of this; should this not be 100% or is it a case of sometimes it should, sometimes it shouldn't.  In that case we would need another class.  Otherwise, the css that's causing this appears to be https://github.com/crimethinc/website/blob/master/app/assets/stylesheets/views/_article.scss#L254

**Comment by veganstraightedge** [comment]
Those old texts are gonna need a lot of hand tuning. They had a lot of old crufty HTML and inline CSS in them. 

But yes, to your point, I think we'll need a case for non-100% width images. As the exception, with 100% as the rule, I think.

**Comment by astronaut-wannabe** [comment]
you might be able to get away with adding `height: auto;` to the image css class. That should stretch/shrink the images height to keep the native aspect ratio ([source][0])

# gif example
![height-auto](https://cloud.githubusercontent.com/assets/13190980/21903110/765be66e-d8b3-11e6-80ef-765a88eb86a2.gif)


[0]:https://stackoverflow.com/questions/12991351/css-force-image-resize-and-keep-aspect-ratio

**Comment by veganstraightedge** [comment]
Good call, @astronaut-wannabe. Wanna submit a pull request?

**Comment by astronaut-wannabe** [comment]
@veganstraightedge will do 👍

**Comment by astronaut-wannabe** [comment]
opened https://github.com/crimethinc/website/pull/216
