### ISSUE TITLE
De-duplicate articles on categories#show page

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1830]
https://crimethinc.com/categories/history

<img width="1244" alt="Screen Shot 2020-10-26 at 12 11 26 AM" src="https://user-images.githubusercontent.com/4361/97143446-f1051800-171f-11eb-84b6-b4fcfd1c4552.png">

**Comment by just1602** [comment]
It is possible that the category controller isn't calling `english` or `prefered_locale`. I had the same issue while adding pagination to category page.
