### ISSUE TITLE
Footnotes attached to the wrong text?

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#185]

**Comment by biofilo** [comment]
https://crimethinc-staging.herokuapp.com/1900/09/11/rncdoc0html

Look at the footnotes at the bottom there! WHAT THE FUCK IS THAT!

**Comment by veganstraightedge** [comment]
Deleted them from this article. 

They were from the SHAC article. No idea how the wires crossed.

https://crimethinc.com/2008/09/01/the-shac-model-a-critical-assessment
