### ISSUE TITLE
Duplication of texts in Feed?

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#186]
If you look, for example, in https://crimethinc.com/2016 , you will see that some texts appear multiple times. I guess those are the cases where there is a blog post and a feature with the same title, or something. In some cases, it might be helpful to have both, as the blog post says something different than the feature. In other cases, it is purely redundant--and in all cases, it looks weird and redundant. I wonder if it would be possible to go through and start to remove the ones that literally offer nothing more than the beginning of the other, longer text?

**Comment by veganstraightedge** [comment]
This is an artifact of how the old site separated "texts" from "blog posts". When both got migrated into one feed, they exposed the duplication that was always there.

Agreed that we should delete the "announcement" posts. The process looks like this:

- Manually scan the yearly feed pages for duplicates
- When a pair is found, determine the canonical one
- Create a redirect from the intro's path to the canonical's path
- Delete the intro article
- Confirm that everything worked out ok

**Comment by veganstraightedge** [comment]
See also:

rncdoc0.html : 2009-05-05
rncdoc1.html : 2009-05-05
rnclegal : 2009-05-05

[PERMIT ME TO POINT OUT THAT THE TEXTS IN THE TWO PREVIOUS ENTRIES ARE IDENTICAL! IDENTICAL! SEEMS TO ME WE ONLY NEED ONE!]

**Comment by biofilo** [comment]
My only caveat here is that, in some cases, the introductory pieces, which would have been on the blog, include a useful paragraph that isn’t in the main feature. Maybe those paragraphs could be included at the beginnings of the features…?

**Comment by veganstraightedge** [comment]
Agreed. We should not go in with a chainsaw. But instead we should be surgical about what we keep and delete.

**Comment by veganstraightedge** [comment]
Will be resolved by #348.
