### ISSUE TITLE
Convert jQuery to vanilla JS in admin date/time polyfill (for published_at times)

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1864]
If we convert this to vanilla Javascript, we'll be one step closer to removing jQuery as an admin dependency. 

https://github.com/crimethinc/website/blob/e0f5f241cb78d3f47833683cd3ce7a0e5f1d2ab0/app/assets/javascripts/admin.js#L25-L42

**Comment by astronaut-wannabe** [comment]
this isn't really an option. The polyfill requires JQuery. I can try to find another polyfill library that doesn't use JQuery under the hood, but don't know of any off of the top of my head.

That said, we can possibly remove the polyfill soon.... 

according to caniuse, date and time attributes are only not there in IE11 and safari desktop:https://caniuse.com/input-datetime

safari desktop looks like it is in the "technology preview" version of the browser, so hopefully soon?
