### ISSUE TITLE
Chaos in the top of podcast #46

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#187]
Maybe this is covered by some other issue already raised about font problems or something, but https://crimethinc-staging.herokuapp.com/2016/02/11/46-international-anarchist-reflections has some chaos at the top of it that I can't see on any other podcast page...

**Comment by veganstraightedge** [comment]
That link isn't to podcast episode 48. 

This one is:

https://crimethinc-staging.herokuapp.com/podcast/48

**Comment by biofilo** [comment]
Ugh, you're dead right. I meant podcast #46!

**Comment by veganstraightedge** [comment]
That also isn't podcast episode 46. 
This is:

https://crimethinc-staging.herokuapp.com/podcast/46

The URL in your issue is just the blob post about episode 46. And I don't see the chaos on my phone. Can you screenshot it and attach it to this issue please?

**Comment by veganstraightedge** [comment]
Oh.  It looks like the image URL is pointing to the wrong place.

**Comment by biofilo** [comment]
![image](https://cloud.githubusercontent.com/assets/24758582/21618708/4376cbba-d1ba-11e6-978f-c9dc8f470a35.png)

**Comment by veganstraightedge** [comment]
@biofilo can you copy/paste into here the URL of the episode image from this link please?

**Comment by biofilo** [comment]
that's the display problem in the chronological feed. And then when I go there, it looks like this:

![image](https://cloud.githubusercontent.com/assets/24758582/21618728/667a2f3a-d1ba-11e6-874f-886042738b6d.png)

**Comment by biofilo** [comment]
But yes, hold on...

**Comment by biofilo** [comment]
http://cloudfront.crimethinc.com/blog/wp-content/uploads/2016/02/1b.jpg

**Comment by veganstraightedge** [comment]
I updated the image URL. Please check it on laptop to see if it's fixed.

**Comment by biofilo** [comment]
Seems to be...
