### ISSUE TITLE
Add 'Languages' to nav bar

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1878]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/4361/99455552-db2ce200-28dc-11eb-95d2-ebb5274d26be.png">

- [ ] Place it between "Search" and "About"
- [ ] Be sure to use the translation, not a string literal

**Comment by QueerSynd** [comment]
Should it link to the section in the footer, or should it be a dropdown with the languages listed?

**Comment by veganstraightedge** [comment]
I think, for now, it should link to https://crimethinc.com/languages

Sorry for not including that in the issue description. I was probably moving too fast when I made it!
