### ISSUE TITLE
Fix broken image URL on Articles

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#193]
- [ ] http://crimethinc.com/2014/08/20/feature-the-making-of-outside-agitators
- [ ] http://crimethinc.com/2014/06/12/feature-why-riot-against-the-world-cup
- [ ] http://crimethinc.com/2014/03/17/feature-the-ukrainian-revolution-the-future-of-social-movements

Do better:
- [ ] http://crimethinc.com/2013/10/04/feature-deserting-the-digital-utopia
- [ ] http://crimethinc.com/2013/10/28/deserting-the-digital-utopia

In the feed listing, not on the actual articles, per se.

**Comment by astronaut-wannabe** [comment]
I wasn't sure what was left to be done on this, as the images seemed to load fine in these articles.

I did notice some of the external link references pointed at 404s, I listed those in the table below along with an archive.org link that can be used to fix them 

---

- http://crimethinc.com/2014/08/20/feature-the-making-of-outside-agitators

     404 link                                                                   | Archive Link                                                                                                            
    --------------------------------------------------------------------------- |------------------------------------------------------------------------------------------------------------------------- 
     http://www.krdo.com/news/agitators-in-ferguson-called-a-disgrace/27612752  | https://web.archive.org/web/20140825023214/http://www.krdo.com:80/news/agitators-in-ferguson-called-a-disgrace/27612752 
     http://www.zinelibrary.info/files/ocor_book_1.pdf                          | https://web.archive.org/web/20140717081139/http://zinelibrary.info/files/ocor_book_1.pdf                                


- https://crimethinc.com/2014/06/12/feature-why-riot-against-the-world-cup

     404 link                                                                 | Archive Link                                                                                                           
    --------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------
     http://www.huffingtonpost.com/2014/06/09/brazil-world-cup_n_5475009.html | https://web.archive.org/web/20151231134310/http://www.huffingtonpost.com:80/2014/06/09/brazil-world-cup_n_5475009.html 



- https://crimethinc.com/2014/03/17/feature-the-ukrainian-revolution-the-future-of-social-movements

     404 link                                                                                                                     | Archive Link                                                                                                                                                        
    ------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------
     http://www.revolution-news.com/ukraine-riots-involuntary-ejaculation-fire/                                                   | https://web.archive.org/web/20150825214031/http://revolution-news.com/ukraine-riots-involuntary-ejaculation-fire/                                                   
     http://www.revolution-news.com/ukrainian-anarchist-dispels-myths-surrounding-euromaidan-protests-warns-of-fascist-influence/ | https://web.archive.org/web/20150924145818/http://revolution-news.com/ukrainian-anarchist-dispels-myths-surrounding-euromaidan-protests-warns-of-fascist-influence/ 



- http://crimethinc.com/2013/10/04/feature-deserting-the-digital-utopia

    404 link                                                      | Archive Link                                                                                             
   ---------------------------------------------------------------|----------------------------------------------------------------------------------------------------------
    http://tmh.floonet.net/articles/abombs.html                   | https://web.archive.org/web/20130310044800/http://tmh.floonet.net/articles/abombs.html                   
    http://crimethinc.com/tools/downloads/pdfs/huntergatherer.pdf | https://web.archive.org/web/20160329080912/http://crimethinc.com/tools/downloads/pdfs/huntergatherer.pdf 



- https://crimethinc.com/2013/10/28/deserting-the-digital-utopia

    Just delete and re-route url to the feature??

**Comment by veganstraightedge** [comment]
Sorry for the delay @astronaut-wannabe. We've been swamped with J20 live blog prep work.

Awesome work on tracking down these dead URLs and their corresponding archive.org link. We'll get these corrected soon.

**Comment by astronaut-wannabe** [comment]
@veganstraightedge no worries, totally understand (and the live blog was great!)
