### ISSUE TITLE
Hero image down on "The secret is to begin" article

### ISSUE THREAD

**Issue by QueerSynd** [crimethinc/website#1975]
On all version of the "The secret is to begin" [article](https://crimethinc.com/2016/09/28/feature-the-secret-is-to-begin-getting-started-further-resources-frequently-asked-questions), the hero image is down:

<img width="1190" alt="Captura de pantalla 2021-01-29 a las 14 51 48" src="https://user-images.githubusercontent.com/76429737/106282904-85ac7400-6241-11eb-81fb-906dcd299782.png">

It seems like Cloudfront is not serving it:
<img width="1168" alt="Captura de pantalla 2021-01-29 a las 14 52 50" src="https://user-images.githubusercontent.com/76429737/106283544-5cd8ae80-6242-11eb-93d1-89ee30a6ca8f.png">

I found the issue when having a look at #1559, I don't believe there is an issue already opened for this.

**Comment by veganstraightedge** [comment]
Oh jeez! Thanks for catching that @QueerSynd. 

The migration script didn't catch all of the "features" CSS because they're in S3 and not in version control. I'll add all of the CSS files to the repo, then we can update them to point to the right URLs.

**Comment by QueerSynd** [comment]
I see it's fixed @veganstraightedge should I close it?
