### ISSUE TITLE
Add link to TCE in the store from TCE page

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#2216]
Since people can order bundles of To Change Everything, we should put a link from the mini-site/page on the .com to the store page.

From:
https://crimethinc.com/tce

To:
https://store.crimethinc.com/products/to-change-everything

**Comment by just1602** [comment]
Where would you put the link? My first thought would be at the complete end, but we probably want it before that?

**Comment by veganstraightedge** [comment]
Great idea. I'll add it to the TCE page in /zines

https://crimethinc.com/zines/to-change-everything

Which is redirected to from `/tce/get`

which is linked to from the "Download PDF" link at the top of `/tce`

**Comment by veganstraightedge** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/4361/230801620-13e83930-9ae0-41d2-a53d-25af43e4ea9a.png">

I added the price and pinned it to the top of /zines 

Thanks @just1602
