### ISSUE TITLE
Extend email/social footer section width to 100% on mobile

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#227]

**Comment by gesa** [comment]
Email/social footer section looks 100% width for me. what viewport/browser?

**Comment by veganstraightedge** [comment]
![screen shot 2017-02-25 at 6 20 54 pm](https://cloud.githubusercontent.com/assets/4361/23336513/3dad6378-fb87-11e6-883a-266e95a94ef5.png)

790px ish wide. Safari.

**Comment by gesa** [comment]
this what you're looking for @veganstraightedge ?

![](https://snaps.akibraun.com/l31bu.png)

**Comment by veganstraightedge** [comment]
That'll do!
