### ISSUE TITLE
Fix Selenium web driver DEPRECATION WARNING

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#2302]
https://stackoverflow.com/questions/69851082/how-do-i-correct-this-selenium-initialisation-command-deprecation-warning

```
2021-12-19 20:05:19 WARN Selenium [DEPRECATION] [:browser_options] 
:options as a parameter for driver initialization is deprecated. 
Use :capabilities with an Array of value capabilities/options if necessary instead.
```

**Comment by just1602** [comment]
I've try to replace the actual code in `spec_helper.rb` as mention in the so post from

```ruby
driven_by :selenium_headless, using: :firefox
```

to

```ruby
options = Selenium::WebDriver::Firefox::Options.new
options.headless!
default_caps = Selenium::WebDriver::Remote::Capabilities.firefox
caps = [options, default_caps]
driven_by Selenium::WebDriver.for(:firefox, capabilites: caps)
```

I've also try this, but I always get the same error : 

```ruby
options = Selenium::WebDriver::Firefox::Options.new
options.headless!
driven_by Selenium::WebDriver.for(:firefox, capabilites: options)
```

The error I got is always this one (the capabilities are empty when using the code without default_caps) :

```
Unable to create a driver with parameters: {:capabilites=>[#<Selenium::WebDriver::Firefox::Options:0x0000555988afafa0 @debugger_address=nil, @options={:browser_name=>"firefox", :args=>["-headless"], :prefs=>{}}, @profile=nil>, #<Selenium::WebDriver::Remote::Capabilities:0x0000555988afaca8 @capabilities={:browser_name=>"firefox"}>]}
```

Also the weird thing is if I don't use the `#headless!` I see a new firefox instance being launch for every integration test, gut the test are still failing saying it was unable to create the driver.

**Comment by just1602** [comment]
Also, if I comment out all the code that configure selenium before each test, it works using chrome, but the warning still appear so maybe I'm doing something wrong or I don't check at the right place, or it's capybara that have to fix the issue!

**Comment by veganstraightedge** [comment]
That's great news!

I love when we can wait for upstream to fix an issue. 

Thanks for investigating this one, @just1602!
