### ISSUE TITLE
Add good title tags to all pages

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#232]

**Comment by astronaut-wannabe** [comment]
what is wrong with the title tag?

for an example, [this article][0] has this title tag:

```html
<title>CrimethInc. : Interview: The Standing Rock Evictions : (Audio and Transcript)</title>
```

unless you mean there are older articles that do not have this format of title tag?

[0]:https://crimethinc.com/2017/02/28/interview-the-standing-rock-evictions-audio-and-transcript

**Comment by veganstraightedge** [comment]
1. The `<title>` tag on most public pages is probably good. Though they should all be audited to make sure that they all have a line like:

https://github.com/crimethinc/website/blob/master/app/controllers/articles_controller.rb#L45

For example, `articles#index` doesn't.
https://github.com/crimethinc/website/blob/master/app/controllers/articles_controller.rb#L7-L9

2. Most of the admin pages don't have any meaningful `<title>` tag. So, my history is flooded with pages just called `CrimethInc.`. It'd be better if they had titles like `CrimethInc. Admin : Editing Article 3 "Article title : subtitle"`. Or something.

Make sense?

**Comment by astronaut-wannabe** [comment]
@veganstraightedge, makes sense, thanks 👍

**Comment by veganstraightedge** [comment]
@astronaut-wannabe Do you want to take on this issue?

**Comment by astronaut-wannabe** [comment]
@veganstraightedge sure!
