### ISSUE TITLE
Handle categories and tags with no articles.

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#243]

**Comment by veganstraightedge** [comment]
@guitsaru Can you take a look at this? It used to work. Something changed. Now when I create an Article and put some Categories in the categories field on `articles/form`, they get saved on Article. But the associations aren't.

Actually, now that I think about it, maybe it's just that future posts aren't showing up on the category page...

**Comment by guitsaru** [comment]
Yep, I'll take a look tonight.

**Comment by guitsaru** [comment]
@veganstraightedge I just tested it locally on dev.  Adding categories seems to work for me, but if you set the published_at in the future it won't show up on the category page.

**Comment by veganstraightedge** [comment]
Makes sense. 

Ok. We should redirect to root if a category page is empty.
