### ISSUE TITLE
Add tiktok account in the footer

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#2453]
We should add the new tiktok account to the footer of the website : https://www.tiktok.com/@crimethinc

@veganstraightedge is there a place where you take the svg icons or you create them by yourself?

**Comment by veganstraightedge** [comment]
I've just found them online in the past. But I don't remember where. I usually tweak their raw XML after downloading them too.

I plan to move us to using the Bootstrap icons for all of the things. So, if you want, in the meantime, you can grab the SVG from their TikTok icon here:

https://icons.getbootstrap.com/icons/tiktok/
