### ISSUE TITLE
Automerge dependabot pull requests

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#2500]
Since we have a lot of pull request coming from dependabot and a test suite we can kind of trust, we should merge dependabot PR when buld are green.

We should inspire ourselves from [this example](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.github/workflows/build.yml#L154-L168)

**EDIT**

After some duckduckgoin maybe we should simply use [this action](https://github.com/marketplace/actions/dependabot-auto-merge)

**Comment by logo4poop** [comment]
I would argue against this from a security point of view is poor. Library developers may push something malicious. Look at leftpad and the like as an example.

**Comment by just1602** [comment]
Yeah, I know, I've think about that... but so far, most dev who push malicious code made a major version to ship their malicious code and this config only merge patched and minor version and we could even reduce it to patch version only.

But yeah, it's a question we should ask ourselves, but in the mean time GitHub need to find a way to make merging those PRs easier.

@veganstraightedge you were the one asking for it. Do we wanna take the risk?

Maybe the other way to do this would be to pre-approve those PRs, so we could simply check the changelog / commit logs and avoid to go in the diff tab to approve the PR before having to click two more buttons to merge it.

**Comment by logo4poop** [comment]
I was looking to see if there was a way to simply combine all of the Dependabot PRs into one. Nothing official, but look at [this.](https://github.com/hrvey/combine-prs-workflow) It seems like a smart way to go about it.

**Comment by just1602** [comment]
I could check, but I don't like this idea since it make commit not atomic anymore. If there's a issue with a gem we update I want to be able to revert this update and only this one, I don't want to revert a whole day of gem update, especially since sometime there's a lot of update in one day or there are major version update that we would not want to downgrade.

**Comment by veganstraightedge** [comment]
I agree with @just1602 that we should not combine Dependabot PRs. We value "make small moves". And this would go against that.

**Comment by veganstraightedge** [comment]
@logo4poop et al, I hear you about the potential for security risk via an upstream addition, a la `leftpad`.

Let's talk that through, as an exercise.

- Did `leftpad` put into their release notes / changeling that it had become malware?
- Would our tests have still all passed with a bad actor like `leftpad`?

These are real questions. I'm open to being convinced either way about this (even though I'm the one who asked for this change). I have other questions, but let's start with those and see where we get.

Let's keep this friendly and open and honest, and get the best result out of our shared conversation.

**Comment by veganstraightedge** [comment]
@logo4poop et al, I hear you about the potential for security risk via an upstream addition, a la `leftpad`.

Let's talk that through, as an exercise.

- Did `leftpad` put into their release notes / changeling that it had become malware?
- Would our tests have still all passed with a bad actor like `leftpad`?

These are real questions. I'm open to being convinced either way about this (even though I'm the one who asked for this change). I have other questions, but let's start with those and see where we get.

Let's keep this friendly and open and honest, and get the best result out of our shared conversation.  

cc: @just1602 @astronaut-wannabe

**Comment by astronaut-wannabe** [comment]
@veganstraightedge I mentioned on the PR that I don't like the idea regardless of the security concerns, that said

> Did leftpad put into their release notes / changeling that it had become malware?

dependabot automatically includes a link to every commit in the PR, so in a way the answer to "Did leftpad put into their [...] changeling [...]?" is "yes"

> Would our tests have still all passed with a bad actor like leftpad?

This is an additional reason why relying solely on our tests to merge a dependabot PR removes a huge part of the value of dependabot. Dependabot includes a compatibility score, which allows us to leverage the CI of every other dependabot user with the same dependencies. You remove that valuable leverage by just relying on our CI

in a hypothetical malicious code update the probability that our CI would fail is low (depending on the dependency and how we use it). In this hypothetical, the probability that **any** depndabot user's CI would fail is much higher than the chance our own CI alone would fail. However, this hypothetical, tail risk distracts from the fact that you are *significantly increasing the probability of merging in dependency bugs in the most common, day-to-day case*

so the answer to your questions are

1. yes
2. The questions should really be, is our CI alone more likely to catch common gem compatibility issues vs the collective CI of every dependabot user

**Comment by astronaut-wannabe** [comment]
All of *THAT* said, i do realize that as an all volunteer project, the value of automating tasks is much higher than it would be in a day-job type situation. So I am fine with this feature if that benefit feels substantial enough to everyone (especially as I have been MIA for awhile)

**Comment by logo4poop** [comment]
I meant colors.js, not leftpad. Leftpad simply got deleted. In both cases the answer is yes. The example was more to show that unchecked merging can be easily be corrupted and cause harm. A benefit in our situation is that the website is mainly comprised of large libraries made by established, more looked over developers. Colors.js was also by an established developer, but he at least alerted that he was going to be shutting it down.

**Comment by just1602** [comment]
This won't be done since we want to check a minimum the changelog of the gem we upgrade.
