### ISSUE TITLE
Videos cannot be watched while browsing privately

### ISSUE THREAD

**Issue by astronaut-wannabe** [crimethinc/website#251]
I don't know if this is something that can be fixed, or if it is required by vimeo, but videos don't work with various browser privacy plugins:

---

<img width="997" alt="1-1" src="https://cloud.githubusercontent.com/assets/13190980/22181001/b5a1c156-e036-11e6-81fc-98f02bce09fa.png">

For example, Privacy Badger breaks the video by blocking vimeo cookies:

<img width="433" alt="1-2" src="https://cloud.githubusercontent.com/assets/13190980/22181002/b5a306d8-e036-11e6-8e87-258f8106708d.png">

**Comment by greggawatt** [comment]
would it be reasonable to roll our own video player here?

**Comment by veganstraightedge** [comment]
We could. We already use a plain `<video>` tag for smaller self hosted videos. 
But for historical reasons, some things are hosted on Vimeo.

Really, all we need to do fix this is remove the domain whitelist on Vimeo for these videos.

**Comment by veganstraightedge** [comment]
@astronaut-wannabe I made all of the embedded videos more public. Can you test them again and see if they play for you? And if so, close this issue please. Thanks.

**Comment by astronaut-wannabe** [comment]
@veganstraightedge still can't play in-line, but now there is a button to click that takes you to vimeo, where you are able to download /watch the video.

I'm good with that. If you are I will close the issue.

<details><summary>Click here for screenshot</summary>
<p>
<img width="980" alt="screen shot 2017-02-03 at 7 08 13 am" src="https://cloud.githubusercontent.com/assets/13190980/22596304/d8fd4b54-e9df-11e6-8e4a-ec6e3328e0d3.png">
</p>
</details>

**Comment by veganstraightedge** [comment]
👍
