### ISSUE TITLE
Offering help

### ISSUE THREAD

**Issue by withoutboats** [crimethinc/website#252]
Hey I do Ruby web dev (as well as other things) and I'd be really glad to help this project. crimethinc had a pretty big & positive impact on my life. Let me know if there's any task I could take on.

**Comment by veganstraightedge** [comment]
@withoutboats Thanks for popping in. We do need help on many things. How about you start with getting the dev setup running on your machine. Then take a look through the issues to see if any things strike your fancy.

If nothing in particular jumps out at you, let me and we'll talk through which issue/s make the most sense. Cool?

**Comment by veganstraightedge** [comment]
Make any progress getting setup ?

**Comment by veganstraightedge** [comment]
When you're ready to jump in, raise a flag. We'll be here.
