### ISSUE TITLE
Turn on GZIP for homepage and favicon.ico

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#254]
http://www.webpagetest.org/result/170123_QP_6AN/1/performance_optimization/#compress_text

**Comment by veganstraightedge** [comment]
Maybe this? 

https://github.com/romanbsd/heroku-deflater

**Comment by brandonparncutt** [comment]
i'm assuming you have nginx in front of this...you can enable gzip compression for a multitude of mime types in nginx

**Comment by veganstraightedge** [comment]
@brandonparncutt I know nothing about nginx config in general and in heroku land in particular. Could you gist up an example of how to do this?

**Comment by veganstraightedge** [comment]
Actually, belay that. In Heroku land, we're not using nginx. We're using Puma.

https://github.com/crimethinc/website/blob/master/Gemfile#L11

**Comment by brandonparncutt** [comment]
Then I defer to your original suggestion of using heroku-deflater...that's probably your best bet. Sorry I didn't do my homework on your stack. That being said...Nginx (like Puma) is great for concurrency...does load balancing, rewrites, caching, and things like gzip compression (and a ton of other cool web functionality) super easy. It's possible to run it in front of Heroku:

https://www.nodebeats.com/documentation/configuring-nginx-on-heroku

Might be something to consider? The site is fantastic by the way. I'm more of a Python person, but I'm a Dev Ops engineer by day. I'd love to contribute any way I can (even if I have to learn a little Ruby).

**Comment by veganstraightedge** [comment]
@brandonparncutt We'll be sticking with Puma. It serves us well and I'm friends with the main dev. Which is handy in a pinch. 

But if you want to dive in and take a stab at Puma + Deflator, that'd be rad.
