### ISSUE TITLE
Turn on browser caching for static assets

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#255]
http://www.webpagetest.org/result/170123_QP_6AN/1/performance_optimization/#compress_text

Leverage browser caching of static assets: 1/100

(No max-age or expires)

**Comment by veganstraightedge** [comment]
@gesa is this something we can do in Cloudfront settings?

**Comment by gesa** [comment]
yup. first we need to set that up in Rails, then we can set it up on the CDN. How does Rails set headers on static assets?

**Comment by veganstraightedge** [comment]
Not sure. I was hoping that you had a magic answer for this one. :D
