### ISSUE TITLE
Fix heading + audio player spacing

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#256]
This used to be good, now it's overlapping.
What happened?

https://crimethinc.com/podcast/53

And to a lesser degree:

https://crimethinc.com/podcast

**Comment by gesa** [comment]
lgtm. Browser/OS/viewport?

**Comment by veganstraightedge** [comment]
Safari on 13" Pro window.

Also on iOS Safari, audio player is just not showing up on the podcast pages now.

**Comment by gesa** [comment]
👍 on it
