### ISSUE TITLE
stealfromwork.crimethinc.com doesn't work

### ISSUE THREAD

**Issue by astronaut-wannabe** [crimethinc/website#257]
The latest column announcement ([Dedans Nous, le Déluge: The Flood Within][0] will potentially lead readers to [stealfromwork.crimethinc.com][1] (it is 2 or 3 clicks away)

That URL results in a security warning in firefox:
![screen shot 2017-01-24 at 4 22 35 pm](https://cloud.githubusercontent.com/assets/13190980/22272887/eb5b9890-e251-11e6-922d-c9378322d951.png)

[0]:https://crimethinc.com/2017/01/24/dedans-nous-le-deluge-the-flood-within-towards-an-aesthetics-of-risk
[1]:https://stealfromwork.crimethinc.com

**Comment by astronaut-wannabe** [comment]
this is fixed https://stealfromwork.crimethinc.com/

**Comment by veganstraightedge** [comment]
Thanks for catching that. I forgot to mark it when I did it.

**Comment by astronaut-wannabe** [comment]
Np 👍
