### ISSUE TITLE
Add visual style for footnotes section

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#261]

**Comment by gesa** [comment]
Can you give me an example to work from? either something in prod or the markup that footnotes will generate

**Comment by veganstraightedge** [comment]
The syntax to make footnotes is two fold.

1. The reference to the footnote is made by `[^1]` or `[^name]`.
2. The footnote itself is anywhere in the document a line (with blank lines above and below it) that starts with `[^1]:`.

For example:

```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad[^1] minim veniam, quis nostrud[^2] exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur[^aki] sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

***

[^1]: Footnote 1.

[^2]: Footnote 2.

[^aki]: Footnote Aki.

```

**Comment by veganstraightedge** [comment]
An example in prod: 

https://crimethinc.com/2009/05/05/going-it-alone

**Comment by veganstraightedge** [comment]
Note that any example in production that has an `<hr>` between the content and the footnotes was just a quick and dirty stop gap put in place by me for readability and visual hierarchy until this issue could be done. After this issue is done, I plan to remove all the `<hr>` tags.
