### ISSUE TITLE
Recursive tag creation on Page

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#271]
I haven't tested on Articles yet.

Locally, in development, when I create a Page and tag it "foo, bar", the two tags are created.

If I edit that page, then save, the tags are duplicated. "foo, foo, bar, bar".

This happens with each successive update.

**Comment by veganstraightedge** [comment]
@withoutboats

**Comment by withoutboats** [comment]
I know what this is, will have a PR in a few minutes.
