### ISSUE TITLE
Add "projects" to the site map under "articles"

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#275]
please!

**Comment by veganstraightedge** [comment]
What should the top level label ("Projects") link to? 

What children items should be listed under it?
What should they link to?

**Comment by biofilo** [comment]
Let's say it should link to 
https://crimethinc.com/categories/projects

with this item:

https://crimethinc.com/2017/01/31/help-us-publish-books-about-borders-and-democracy-no-wall-they-can-build-from-democracy-to-freedom

We can add more to it soon?
