### ISSUE TITLE
Re-link to archive.org pages for dead link

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#283]
From #193 by @astronaut-wannabe:

***

I wasn't sure what was left to be done on this, as the images seemed to load fine in these articles.

I did notice some of the external link references pointed at 404s, I listed those in the table below along with an archive.org link that can be used to fix them 

---

- [x] http://crimethinc.com/2014/08/20/feature-the-making-of-outside-agitators

     404 link                                                                   | Archive Link                                                                                                            
    --------------------------------------------------------------------------- |------------------------------------------------------------------------------------------------------------------------- 
     http://www.krdo.com/news/agitators-in-ferguson-called-a-disgrace/27612752  | https://web.archive.org/web/20140825023214/http://www.krdo.com:80/news/agitators-in-ferguson-called-a-disgrace/27612752 
     http://www.zinelibrary.info/files/ocor_book_1.pdf                          | https://web.archive.org/web/20140717081139/http://zinelibrary.info/files/ocor_book_1.pdf                                

- [x] https://crimethinc.com/2014/06/12/feature-why-riot-against-the-world-cup

     404 link                                                                 | Archive Link                                                                                                           
    --------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------
     http://www.huffingtonpost.com/2014/06/09/brazil-world-cup_n_5475009.html | https://web.archive.org/web/20151231134310/http://www.huffingtonpost.com:80/2014/06/09/brazil-world-cup_n_5475009.html 

- [x] https://crimethinc.com/2014/03/17/feature-the-ukrainian-revolution-the-future-of-social-movements

     404 link                                                                                                                     | Archive Link                                                                                                                                                        
    ------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------
     http://www.revolution-news.com/ukraine-riots-involuntary-ejaculation-fire/                                                   | https://web.archive.org/web/20150825214031/http://revolution-news.com/ukraine-riots-involuntary-ejaculation-fire/                                                   
     http://www.revolution-news.com/ukrainian-anarchist-dispels-myths-surrounding-euromaidan-protests-warns-of-fascist-influence/ | https://web.archive.org/web/20150924145818/http://revolution-news.com/ukrainian-anarchist-dispels-myths-surrounding-euromaidan-protests-warns-of-fascist-influence/ 

- [x] http://crimethinc.com/2013/10/04/feature-deserting-the-digital-utopia

    404 link                                                      | Archive Link                                                                                             
   ---------------------------------------------------------------|----------------------------------------------------------------------------------------------------------
    http://tmh.floonet.net/articles/abombs.html                   | https://web.archive.org/web/20130310044800/http://tmh.floonet.net/articles/abombs.html                   
    http://crimethinc.com/tools/downloads/pdfs/huntergatherer.pdf | https://web.archive.org/web/20160329080912/http://crimethinc.com/tools/downloads/pdfs/huntergatherer.pdf 

- [x] https://crimethinc.com/2013/10/28/deserting-the-digital-utopia

    Just delete and re-route url to the feature??

**Comment by veganstraightedge** [comment]
Keep in mind that the static versions of these texts that are in `db/seeds/articles` are only used for dev setup at this point. The real article data lives in the database in production. IMO, the best way to address this is to write a script that I could then run in production to update those articles' content.

**Comment by astronaut-wannabe** [comment]
I assumed someone with admin access would just read the `content` issues and just edit the articles in prod

I can write an update script

**Comment by aspleenic** [comment]
Tried looking into building a rake task to handle this but it would require replacing all the text of the article, which is likely to bogdown the deploy when the task runs.

Will work on a script of some sort. Suggestions welcome.

**Comment by veganstraightedge** [comment]
Manually copy/pasted these in the production database. I'm not too worried about the old seeds files having the wrong URL. 

Thanks for looking into this before, @aspleenic.

Thanks for compiling this list, @astronaut-wannabe.
