### ISSUE TITLE
Add next/prev year/month links to pagination for date collections

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#294]
Add a new line of pagination navigation under the current pagination.

# For year collections

Let's use `/2016` for this example.

- [ ] Add "< Next Year (2017)" link
- [ ] Add " (2015) Previous Year >" link

# For month collections 

Let's use `/2016/01` for this example.

- [ ] Add "< Next Month (2016-02)" link
- [ ] Add " (2015-12) Previous Month >" link

# Exceptions

In all cases, 

- [ ] Don't add a "Previous" link if the current page is the oldest year 
- [ ] Don't add a "Next" link if the current page is the latest year 

Same for months, 

- [ ] Don't add a "Previous" link if the current page is the oldest month
- [ ] Don't add a "Next" link if the current page is the latest month

# Gap Years

As show on https://crimethinc.com/read#years, we don't have any Articles published in 1998 or 1999. It'd be best if, when linking to next/previous, the links could jump from 1997 to 2000 and vice versa.

**Comment by guitsaru** [comment]
@veganstraightedge How do we want to handle this in the case that a given month/year only has one article?  Currently that will redirect to the article itself.  Do we want to keep this behavior?

**Comment by veganstraightedge** [comment]
Good catch!

I think we lose that behavior for redirecting when `year` or `year/month` only has one article. But we keep it for when a day only has one.

This new behavior should take precedence.
