### ISSUE TITLE
Tools price doesn't match between website and store

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#2995]
If you take the first zine on `/tools`, it state that it ise 25 copies for $2.50. On the store, it's 25 copies for $5.50 and on the zine description on the store it says 25 copies for $3.50.

Maybe that $5.50 for one copy and $3.50 for 25 copies, which would be fine, but I'm wondering if there's an api we could fetch to display the price on the website.

**Comment by veganstraightedge** [comment]
thank you! fixed it 

it's now sold out altogether, so I removed the buy now price entirely and moved it off the top of /zines
