### ISSUE TITLE
Extend media embed syntax for link URLs

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#303]
Currently this embed code:

```
[[http://example.com Caption text.]]
```

will create this HTML:

```html
<figure>
  <img src="http://example.com" />
  <figcaption>Caption text.</figcaption>
</figure>
```

***

If you want to make the image a clickable link, you can't use the embed code and instead have to write this HTML manually:

```html
<figure>
  <a href="http://example.com/link"><img src="http://example.com" /></a>
  <figcaption>Caption text.</figcaption>
</figure>
```

***

Current idea for extending the `[[ ]]` syntax:

```
[[EMBED_URL OPTIONAL_LINK_URL Optional caption text.]]
```

This would require the implementation to inspect the second thing after space separation and see if it it looks like a URL. If so, treat it as a link and the thing after the next space as the caption. If not, treat it as a caption. Seems doable.

Where it gets more complicated is if the `EMBED_URL` or `OPTIONAL_LINK_URL` are actually paths instead of URLs. A little trickier to discern them from the optional caption text.

***

I'm open to other ideas.

**Comment by veganstraightedge** [comment]
@bookis @biofilo @guitsaru @faun @gesa @eliduke @carols10cents @astronaut-wannabe @withoutboats @steveklabnik @mutantmonkey

**Comment by steveklabnik** [comment]
Have you looked at how commonmark or anything does this, if at all?

**Comment by astronaut-wannabe** [comment]
I just want to make sure I am understanding the terminology here. Is "media embed" specifically talking about 3rd party media (e.g. vimeo, youtube), or is this just going to be how authors type a clickable image into their markdown file?

will this eventually end up being rendered in [/articles/embeds/_image.html.erb][0]?

if this is just to let authors more easily include clickable images into their markdown without having to worry about manually typing the HTML for that, then I like your suggestion.

> Where it gets more complicated is if the EMBED_URL or OPTIONAL_LINK_URL are actually paths instead of URLs. A little trickier to discern them from the optional caption text.

you could just go easy on yourself and make the syntax something like
``[[EMBED_URL link:OPTIONAL_LINK_URL Optional caption text.]]``
or
``[[EMBED_URL path:OPTIONAL_LINK_URL Optional caption text.]]``
to make the regex easier

[0]:https://github.com/crimethinc/website/blob/a245e052cbee92676fcb9d85f9163cb2046e2fb0/app/views/articles/embeds/_image.html.erb

**Comment by veganstraightedge** [comment]
@steveklabnik I've looked around some. AFAIK, this kind of this is much higher level than any of the Markdown flavors. Even the simple `[[URL to heterogeneous media to embed]]` is already higher level than what the Markdown flavors do.

**Comment by veganstraightedge** [comment]
@astronaut-wannabe This is what I'm trying to _improve_ for our writers, most of which are not very technical. Even those of us who are more technically experienced still often mess up the Markdown syntax for image + link.

``[![alt text][3]][4]``
``[3]:https://cloudfront.crimethinc.com/assets/articles/2017/02/14/crimethinc-valentine.jpg``
``[4]:https://crimethinc.com/2017/02/14/say-it-with-barricades-the-difference-between-peace-and-love``

In my opinion, this is too much syntax and too easy to fuck up. Even it wasn't, it doesn't provide an answer for using `<figure>` and `<figcaption>` for captions on images.

Also, my `[[ ]]` media embed syntax addition (that gets processed before Markdown processing) supports more than just images:

- audio
- video 
- Tweet 
- Vimeo 
- YouTube 

And I have plans for others.

- Twitter video
- Instagram
- Vine
- Facebook video 
- and others and necessary

***

I'm not looking for The Markdown Way™ of doing this thing, I'm looking to create a higher level (opinionated) way of doing this thing that supports *our* use case. Does that make sense?

**Comment by astronaut-wannabe** [comment]
@veganstraightedge got it 👍 

 in that case, I go with my original comment and say your idea seems like the nicest syntax to use while typing articles  

I also thought about it more and I also don't think my suggestion of adding `link:` or `path:` really adds anything.

The format you suggested is already space delimited on the first 2 tokens

**Comment by guitsaru** [comment]
I just pushed #304 based on @veganstraightedge's original suggestion.

**Comment by veganstraightedge** [comment]
@guitsaru I appreciation your gumption! But I want to let this ruminate for a few minutes before deciding on a syntax. I don't want to introduce a syntax, have writers using, realize a change, then have to re-train writers AND change previously used instances of it.

**Comment by guitsaru** [comment]
@veganstraightedge I get that, I just happened to have it open and felt like trying.  It doesn't need to be merged yet.

**Comment by veganstraightedge** [comment]
Grool.

**Comment by gesa** [comment]
when i think about the custom Jekyll tags i've implemented in the past for non-programmers, something _resembling_ html's syntax has been p succesful.  por ejemplo

```
[[ image=http://example.com/image.jpg link=http://example.com caption="This is a string that non-programmers are surprisingly good at recognizing needs to be in quotes" ]]
```
 or 
```
[[ video=https://www.youtube.com/watch?v=0MUsVcYhERY caption="This is literally the funniest video on the internet" ]]
```
 or 
```
[[ video=http://snaps.akibraun.com/lm54h.mp4 caption="As it turns out this might also be the funniest video on the internet" ]]
```

the idea being, our code can look at `video` and try to figure out is this something we already have boilerplate embed code for? ( `/youtube\.com/`, `vimeo\.com` ) or do we need to generate a `<figure>` with a `<video>` element? same for `audio` and soundcloud vs bandcamp vs `<audio>` and if there's a `link` param, wrap the whole damn thing in an anchor tag

**Comment by veganstraightedge** [comment]
@gesa I feel like that's too much syntax too. 
While, I *get* it. But it's a lot of punctuation and attr names to remember.

Especially for non-technical folks and ESL folks.

**Comment by gesa** [comment]
how about 
```
[[ http://object.source.url "Caption in quotes" http://optional.link.url ]]
```
and we just hold our breath and hope we can parse it?

**Comment by veganstraightedge** [comment]
That's not bad.

**Comment by guitsaru** [comment]
How important is backwards compatibility?  If we change how captions are parsed will we need to edit a bunch of articles?

**Comment by veganstraightedge** [comment]
Backward compatibility is *not* important. We've only used this `[[ ]]` syntax in a few articles so far. I'm fine with back-fixing them.

**Comment by veganstraightedge** [comment]
@gesa I've noodled on it some more and came to this (I think) conclusion.

```
[[ https://example.com/path/to/media Optional caption, but with no quotes. /path/to/link]]
[[ https://example.com/path/to/media Optional caption, but with no quotes. https://example.com/path/to/link]]
```

When parsing, we can still easily separate by space, then if if the thing after the last space looks like a URL or a path that must start with a slash, then we link it. Otherwise, its behavior works as it does today.

As it turns out, that also gives us backward compatibility. And that's a nice little bonus.

Any objections to this syntax?

**Comment by veganstraightedge** [comment]
@guitsaru Would you like to adjust your PR to work with this syntax?

**Comment by guitsaru** [comment]
@veganstraightedge Yup, updated #304.
