### ISSUE TITLE
Change blockquote css

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#307]
- [ ] No biggness
- [ ] No boldness
- [ ] Same styles as normal content `p`
- [ ] Margin around the whole thing by a line or two (slightly more than the normal `p + p` distance)

**Comment by veganstraightedge** [comment]
Per @biofilo's request

**Comment by gesa** [comment]
@biofilo @veganstraightedge how do you feel about using a line to indicate block-quotiness?

![pz8xp](https://cloud.githubusercontent.com/assets/782056/23107000/afd7441e-f6aa-11e6-9236-09f2b57659e2.png)

**Comment by veganstraightedge** [comment]
Seems good to me. 

@biofolo how is this to you?

**Comment by biofilo** [comment]
Awesome! Well done everyone!
