### ISSUE TITLE
Vertical align title/subtitle better

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#313]
The CSS that I used to vertically align title/subtitle on an article was re-used from a project from a few years ago. Definitely before flex box/grid stuff was operational.

I feel like it's fragile and kinda not great, as is.

I think we should move it to some new hotness that does vertical centering betterer.

***

Here's an example of it kinda busted.

![screen shot 2017-02-21 at 10 46 31 pm](https://cloud.githubusercontent.com/assets/4361/23200193/df029a8e-f887-11e6-92cb-0b59b56e5fa8.png)

**Comment by gesa** [comment]
@veganstraightedge I'm trying to reproduce but having a hard time. what viewport was that screenshot taken at?

**Comment by gesa** [comment]
actually nevermind.

**Comment by veganstraightedge** [comment]
Take a look at the latest batch of homepage article. Their vertical alignment is good on the homepage. But is all over the place on the article page for each. Please investigate further.

**Comment by veganstraightedge** [comment]
![screen shot 2017-02-22 at 11 15 41 pm](https://cloud.githubusercontent.com/assets/4361/23248583/ddfdf034-f954-11e6-8a62-dff00999c400.png)


Images are no long being scaled to full width anymore either.

**Comment by veganstraightedge** [comment]
@gesa 👆
