### ISSUE TITLE
Add #id to the end of [[ ]] embed syntax

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#316]
Ok. Here's another (and I think the final) addition to `[[ ]]`.

The need to be able to apply an `id=...` to the outer wrapper of whatever media is embedded (`<figure>`, `<div class="video-container">`, etc).

I think we tack it on the end and then look at the last two things for URL/id formatting. Thing is both are optional and id doesn't require a link URL.

Here are some examples.

```
[[ https://example.com/image.png ]]
[[ https://example.com/image.png Optional caption. ]]

[[ https://example.com/image.png optional caption /path/to/link ]]
[[ https://example.com/image.png optional caption https://example.com/path/to/link ]]

[[ https://example.com/image.png #id ]]
[[ https://example.com/image.png optional caption #id ]]

[[ https://example.com/image.png optional caption /path/to/link #id ]]
[[ https://example.com/image.png optional caption https://example.com/path/to/link #id ]]

[[ https://example.com/image.png optional caption #id /path/to/link ]]
[[ https://example.com/image.png optional caption #id https://example.com/path/to/link ]]
```

**Comment by veganstraightedge** [comment]
Does this seems reasonable, both design and feasibility?

**Comment by guitsaru** [comment]
I think it's doable, but I'm not sure about the syntax.  What if they intend to use a caption like "Image #1"?

Do you think that's a reasonable trade-off?

**Comment by veganstraightedge** [comment]
Good thinking. What about adding some more syntaxiness, since its a less common case, like this?

`[[ https://example.com/image.png optional caption /path/to/link id:some-id-value ]]`

**Comment by guitsaru** [comment]
Yep. That should work. I'll add work on it tomorrow.
