### ISSUE TITLE
Pipes in URL

### ISSUE THREAD

**Issue by benatcwc** [crimethinc/website#317]
The pipes in the Google Translate URL screwed up the formatting here: https://crimethinc.com/admin/articles/159

Let's make the pipes not screw up the formatting.

**Comment by veganstraightedge** [comment]
I fixed this in two ways:

1. The trailing pipe was unnecessary, so I dropped it.
2. I escaped the first pipe which tells the kramdown parser to ignore it as a special character and treat it as a literal character.

I did that with a  slash.

***

This:
`http://translate.google.com/#ru|en`

Became this:
`http://translate.google.com/#ru\|en`
