### ISSUE TITLE
Don't try to create a Redirect when short_path is empty

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#340]
1. Edit an existing `Article` in the admin CMS
2. Delete the `short_path` field's contents.
3. Get error: `Short path has already been taken.`

***

This shouldn't happen. This code path should be skipped if `short_path` is `blank?`.

**Comment by veganstraightedge** [comment]
@greggawatt

**Comment by greggawatt** [comment]
Should short_path be required?

**Comment by greggawatt** [comment]
Hi there, Is this fixed by the push of my new code for this?

**Comment by veganstraightedge** [comment]
`short_path` should not be required. Though in practice most all articles will have it, though only after some date in the past.

**Comment by veganstraightedge** [comment]
And you're right, this is fixed by your newer code.
