### ISSUE TITLE
Re-work site layout using css grid

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#346]
Experimental?

https://alistapart.com/article/practical-grid

What's the browser support look like for this?
Is it still too early?

**Comment by gesa** [comment]
Definitely too early to implement but i'm looking forward to more browser adoption bc this is gonna be the besssttttttt 


![eiodt](https://cloud.githubusercontent.com/assets/782056/24329362/36b5e8b8-11b9-11e7-84d2-0a99c733fdd0.png)
_browser versions weighted by global usage_

**Comment by veganstraightedge** [comment]
Thanks
