### ISSUE TITLE
Add rel-next and rel-prev link tags

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#361]
https://github.com/kaminari/kaminari#the-rel_next_prev_link_tags-helper-method

Not on all pages. Only ones that have pagination, namely Articles (singular and collections).
That includes the homepage.

**Comment by guitsaru** [comment]
@veganstraightedge did you want this on the admin pages too?

**Comment by veganstraightedge** [comment]
Nah. This is mostly a hint for search engine. I'm not even sure if browsers use them to prefetch. Even if they do, that doesn't really apply to our /admin usage.
