### ISSUE TITLE
Move helper specs to controller spec

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#371]
I commented out three failing specs in `application_helper_spec` after I moved some helpers to `application_controller` (which broke the specs). 

The specs need to be moved and changed.

OR

The code needs to be implemented differently in `feed.json` to not need them to be in `application_controller`. I'm open to either.

**Comment by veganstraightedge** [comment]
@guitsaru Would you mind doing this for me? I started trying to move the specs and then was like O_o in RSpec land. ( I'm bad at testing :( )

**Comment by guitsaru** [comment]
Yep, no problem
