### ISSUE TITLE
Logos svg format

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#389]
I think it could be nice to have svg version of the logos. It's very usefull especially when you want to print stuff like, t-shirt, hoodie, stickers, etc.

**Comment by veganstraightedge** [comment]
Agreed. We have the code to show them, just no SVG files yet. Would you be able to convert any of the logos into high quality SVG vectors?

**Comment by just1602** [comment]
I could basically convert them with imagemagick, but I'm not able to cleanly convert them in svg with illustrator and inkscape..

**Comment by veganstraightedge** [comment]
Can you upload the imagemagick conversion so I can see their quality please?

**Comment by just1602** [comment]
boat.svg : https://share.riseup.net/#cJPgVpJUBUVPqz3PBQU_Iw
bulb-and-bones.svg : https://share.riseup.net/#TJaCK2br-faxHQtgQHyQkA
bullet.svg : https://share.riseup.net/#YfzVaReVlNO901Rqidq0uA
hand.svg : https://share.riseup.net/#6dGETCmoLZXVQf9MOg65Ng
pfmag.svg : https://share.riseup.net/#5HWkPYbRMaK3lRlQ19mHPA
wrench.svg : https://share.riseup.net/#okI1kL2YdsCRXKbAUUvJWg

**Comment by veganstraightedge** [comment]
@just1602 Thanks!

Updated the `Tools : Logos` page.

https://crimethinc.com/logos

**Comment by veganstraightedge** [comment]
@just1602 Also, feel free to stick around. If there are any other issues that seem like they're in your wheelhouse, go for it! We can always use more help.
