### ISSUE TITLE
Update Bootstrap (for admin) to v4.a6

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#393]

**Comment by just1602** [comment]
Ruby noob question. :D 

A v4.a6 ruby gem only exists for [bootstrap](https://rubygems.org/gems/bootstrap) and not for [bootstrap-sass](https://rubygems.org/gems/bootstrap-sass).

Do you think we can change on for the other or you have done some customization to bootstrap-sass and we need to wait tor the boostrap-sass gem ?

**Comment by veganstraightedge** [comment]
`gem "bootstrap", "~> 4.0.0.alpha6"` is good
