### ISSUE TITLE
Broken image and unsecure page

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#403]
In [this article](https://crimethinc.com/2017/05/10/popsec-inglourious-basterds-operational-security-lessons-learned-from-scalping-nazis) the last image is broken and since it was take from an insecure connection, the page is mark as not secure by firefox.

[There](https://web.archive.org/web/20170511120733/http://img.pandawhale.com/post-39026-I-dont-think-so-more-like-chew-pzfZ.gif) is the missing gif.

I'm wondering, is this the right place to open that kind of issue?

**Comment by veganstraightedge** [comment]
Thanks. Fixed.
