### ISSUE TITLE
Summary field not counting characters

### ISSUE THREAD

**Issue by benatcwc** [crimethinc/website#407]
The Summary field isn't counting characters. Neither is the Tweet field.

**Comment by astronaut-wannabe** [comment]
I cannot reproduce on master. Is there a way to know what the latest commit in production is?

![count](https://user-images.githubusercontent.com/13190980/29179855-806cf1d4-7dfe-11e7-842a-e5f5054f50ca.gif)

**Comment by veganstraightedge** [comment]
Staging and Production are running latest (as of right now now) commit. 

9dfda371

It doesn't work in either place. Interesting. Must be an environmental thing.

**Comment by veganstraightedge** [comment]
Adding `tether` fixed this.
