### ISSUE TITLE
Add UTC time note to Article form

### ISSUE THREAD

**Issue by benatcwc** [crimethinc/website#408]
Can we add an example to the description of doing UTC time? Something like "If you want the post to get posted at X time, put in Y time"...

**Comment by veganstraightedge** [comment]
@just1602 Wanna take a crack at this one?

We tend to publish at 10am US west coast time (PST/PDT). I think that's 19:00 UTC. But could you calculate and add a note?

**Comment by just1602** [comment]
Yeah I can check this!
