### ISSUE TITLE
Re-flow categories and tags form widgets on Article form

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#413]
The list of `categories` has grown long on the Article form. It'd be better presented as two columns.

It currently takes up a quarter column of space. It could take of half as two quarter columns. 

The `tags` form group can then be moved to the other half of space next to it.

***

Hint, Rails has `.in_groups_of(2)` that you can use to break the categories up into two columns.

**Comment by veganstraightedge** [comment]
@just1602

**Comment by just1602** [comment]
Hey @veganstraightedge, for the form, do you directly use simple_form or you use something else? I try to find something in the doc and it's not really clear to me! :P

**Comment by veganstraightedge** [comment]
We don't use simple_form at all. But you know what. I can get this one since it's a little heavier on the Ruby/Rails.

**Comment by just1602** [comment]
Nah it's ok, I'm almost done and if I want to learn ruby/RoR someday I've to jump in some code and look how it works. :)

**Comment by veganstraightedge** [comment]
Ok! Good luck. Beep me if you want to screen pair or have questions.
