### ISSUE TITLE
Add published_at / draft mode to Tools

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#416]
- [ ] Only show published ones on /tools pages, like Article etc

**Comment by greggawatt** [comment]
id like to start on this one this week, Anything I need to know about it?

**Comment by veganstraightedge** [comment]
Look to `Article` for model attributes, scopes and UI. `Status` and `published_at` are the big ones.

**Comment by greggawatt** [comment]
just to clarify, by tools you mean the logo, sticker, zine, poster, and video models right?

**Comment by veganstraightedge** [comment]
yes and...

- books and zines both use the Book model
- stickers and posters both use the Poster model
- logos are Logo
- videos are Video

**Comment by greggawatt** [comment]
I'm thinking for this a parent model might make sense with all the published logic in it so it's consistent across all models. If not that, maybe a shared library? Kinda curious about architecture thoughts here.

**Comment by veganstraightedge** [comment]
it feels like a situation where a Concern could be useful.

See what @guitsaru has already done with concerns so far.

https://github.com/crimethinc/website/tree/master/app/models/concerns

**Comment by greggawatt** [comment]
I'm making a concern called publishable to take care of this. I see the following in post concern: 
  def published?
    status.name == "published"
  end

I was considering saying
  def published?
    published_at.present?
  end

But it seems like we should be consistent, Should all the tools have status_id as well and we treat everything like a state machine?

**Comment by veganstraightedge** [comment]
Closed by https://github.com/crimethinc/website/pull/483
