### ISSUE TITLE
Add /categories page

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#420]

**Comment by aspleenic** [comment]
Is this a list of categories for how articles, podcasts, etc are related to a specific subject, like tags?

**Comment by veganstraightedge** [comment]
Categories are a pre-set list of groups for Articles.

Tags are free-form per Article.

***

For this page (sorry for the hollow Issue), I'm thinking just a good looking list of linked Category names in bold and in not bold a count of Articles in that Category. 

Don't show any Categories with zero Articles.

Sort by Category name.

***

- **Adventure** (6)
- **Calling All Anarchists** (137)
- **Current Events** (23)
- …
