### ISSUE TITLE
Can there be an option to use multiple colors of text in articles?

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#423]
Or is there already?

**Comment by veganstraightedge** [comment]
Say more about this please. 

Is it one highlight color for all articles?
Is it two or three but the same across all articles?
Is it an arbitrary number per article and arbitrary colors per article?

**Comment by biofilo** [comment]
I would be thrilled if text could appear in, say, blue and red, as well as black. Surely there couldn't be a need for more options than that, but one additional color option would be great, and two would be plenty.

**Comment by veganstraightedge** [comment]
darkred #8B0000
darkgreen #006400
olive #808000
steelblue #4682B4
deeppink #FF1493
slategray #708090
goldenrod #DAA520

- [ ] Add `text-color-name` css classes for each of those colors
- [ ] Add a note or two on article form on colors and syntax
- [ ] `{: .css-class-name}
