### ISSUE TITLE
Suggest further reading at the bottom of each article?

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#424]
When someone gets to the bottom of an article, it would be nice if they have the option to read another article or two. I'd arrange for the bottom of the page to display the most recent couple articles in each of the categories that apply to the article they just read.

It shouldn't take up too much space, but I think it could be a good thing.

**Comment by veganstraightedge** [comment]
How would these recommendations be derived?

Manually added by a human?
Or algorithmicly by computer?

**Comment by biofilo** [comment]
I'm imagining the computer automatically offering links to the most recent couple articles in each of the categories that apply to the article they just read.

**Comment by biofilo** [comment]
So at the bottom of an article that is in the categories "art" and "news" we would see, say, the most recent previous two "art" articles and the most recent two "news" articles.

**Comment by veganstraightedge** [comment]
If the algorithm is simply, the most recent two articles in each category that this article is in, that's pretty doable. 

But if there's an expectation of unearthing deep cuts, that's much hard.

**Comment by biofilo** [comment]
No, I want the simplest version!
