### ISSUE TITLE
[Feature Suggestion] Make publication_date section more human-friendly

### ISSUE THREAD

**Issue by astronaut-wannabe** [crimethinc/website#431]
We could use the [timezone rails helper][0] along with the new native HTML5 `date` and `time` form elements to get a (maybe) more familiar user experience when setting `published_at`

The HTML5 elements work in chrome ([caniuse][1]) and could be polyfilled for firefox ([polyfill tutorial][2])

This would only affect the UI (in the backend we would still make a UTC date doing `Time.parse(date+time+time_zone)`)

I did a quick prototype to what that UI might look like:

<details>
<summary>native chrome (no pollyfill)</summary>

<br>

![datetime](https://user-images.githubusercontent.com/13190980/29263237-aa548838-80e0-11e7-9103-8d7b28019723.gif)
</details>

[0]:http://guides.rubyonrails.org/form_helpers.html#time-zone-and-country-select
[1]:https://caniuse.com/#feat=input-datetime
[2]:https://code.tutsplus.com/tutorials/quick-tip-create-cross-browser-datepickers-in-minutes--net-20236

**Comment by veganstraightedge** [comment]
I'm not *opposed* to it. Here are my questions:

1. Can it work across our browser matrix? That's not just Chrome and Firefox. It's also Safari and MobileSafari (iOS). Possibly IE11 or Edge. And mobile Chrome (Android).

2. Can you put the 2 most common timezones at the top of the select before then listing all timezones? US West Coast and US East Coast. Most articles are timed for US West Coast 10a as our point of reference.

3. I see that you have "Back to Top", so you've recently pulled. Did you see the `Publish NOW!` UI on new and unpublished Articles? That needs to stay, even if we use this. Because sometimes an Article needs to go out now, and someone spending any effort picking a time is too much and is prone to human error.

**Comment by astronaut-wannabe** [comment]
> 1. Can it work across our browser matrix? That's not just Chrome and Firefox. It's also Safari and MobileSafari (iOS). Possibly IE11 or Edge. And mobile Chrome (Android).

safari and IE are the only that don't support it (but I could polyfill, or even just make the view do something like `render original_datetime_partial if ie? || safari?`

it is done in firefox (just behind a feature flag at the moment), done in Edge, and you get pretty nice keyboard support in ios11 and android.

> 2. Can you put the 2 most common timezones at the top of the select before then listing all timezones? US West Coast and US East Coast. Most articles are timed for US West Coast 10a as our point of reference.

yes!

> 3. see that you have "Back to Top", so you've recently pulled. Did you see the Publish NOW! UI on new and unpublished Articles? That needs to stay, even if we use this. Because sometimes an Article needs to go out now, and someone spending any effort picking a time is too much and is prone to human error.

totally do-able. this change really wouldn't affect any logic, only UI. But just to be sure should probably put in feature specs first

**Comment by veganstraightedge** [comment]
> > Can it work across our browser matrix? That's not just Chrome and Firefox. It's also Safari and MobileSafari (iOS). Possibly IE11 or Edge. And mobile Chrome (Android).

> safari and IE are the only that don't support it (but I could polyfill, or even just make the view do something like render original_datetime_partial if ie? || safari?

> it is done in firefox (just behind a feature flag at the moment), done in Edge, and you get pretty nice keyboard support in ios11 and android.

1. What is the level of effort / difficulty to polypill it? All things being equal, I'd prefer to have UI for all users.
2. Can you post a screenshot of the iOS / android UIs please?

**Comment by astronaut-wannabe** [comment]
> What is the level of effort / difficulty to polypill it? All things being equal, I'd prefer to have UI for all users.

not hard, plenty of tutorials around. Hardest part will be finding a copy of IE to test on 🙃

> Can you post a screenshot of the iOS / android UIs please?

yes. gimme a moment to find a phone (I dont currently have one)

**Comment by veganstraightedge** [comment]
Ok. This sounds interesting and promising. Go for it!

**Comment by astronaut-wannabe** [comment]
ok, first of all, I just learned about `rails server -b 0.0.0.0` which lets you access your rails dev server from any device on your network. very handy for mobile

second, for ios (obviously I would need to fix the CSS), you can see how you get a handy date-picker keyboard (time also gives you a fancy time-picker keyboard).

<img src="https://user-images.githubusercontent.com/13190980/29264841-458639cc-80e7-11e7-9782-abb4edb81e81.jpg" alt="ios screenshot" width="40%"></img>

**Comment by veganstraightedge** [comment]
Fuck yeah on both

**Comment by astronaut-wannabe** [comment]
resolved in #436
