### ISSUE TITLE
Make all articles header image square on mobile

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#445]
Like the lead article on homepage feed, all articles (on homepage and on article page) should have a header image that is square. 

- [x] CSS crop landscape photo to square on mobile
- [ ] Add `mobile_image` field to `Article`
- [ ] Add code to switch between the two (mobile and non) images based on screen size

**Comment by veganstraightedge** [comment]
![image_uploaded_from_ios_720-1](https://user-images.githubusercontent.com/4361/29398002-c04fe07c-82d6-11e7-864d-49679eae6e7f.jpg)

**Comment by gesa** [comment]
@veganstraightedge i wonder if maybe we don't need to do any of those three checkboxes? https://github.com/crimethinc/website/commit/e4cdafd169b37dc6eae28cb3b5e303a335e49c63

**Comment by veganstraightedge** [comment]
Yes and no, I think.

Part of the motivation for a separate `mobile_image` is be able to chose where the crop is and to send a smaller (file size) image for "mobile" than for desktop.
