### ISSUE TITLE
Add [[]] for Twitter video (minus tweet text)

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#449]
https://twitter.com/Breaking911/status/900211169734131713

`^` : `Embed Video`

***

In repo:

https://github.com/veganstraightedge/markdown_media

**Comment by veganstraightedge** [comment]
@guitsaru How do you think we should do this? Best I can tell, the standalone video doesn't have its own URL.

**Comment by guitsaru** [comment]
@veganstraightedge: We might want to start looking into using oEmbed:

[https://publish.twitter.com/oembed?url=https://twitter.com/Breaking911/status/900211169734131713]()

```json
```

**Comment by guitsaru** [comment]
Although, looking at the response it doesn't seem that much different.  Does the js library not do videos automatically?

I'll look into it a bit more.

**Comment by veganstraightedge** [comment]
It embeds the video, yes, but it also still includes the tweet text.

**Comment by guitsaru** [comment]
Looks like if we set the blockquote to `<blockquote class="twitter-video" data-status="hidden">` it'll do what you're wanting.  So we just need a way to tell it that it's a video.

**Comment by veganstraightedge** [comment]
Both of those seem reasonable to me.

**Comment by veganstraightedge** [comment]
On closer inspection, oEmbed doesn't really get us anything better than our `.erb` template. It adds an extra HTTP request though.

Do you want to implement the `type:video` flag? 

Also, what's your rubygems.org email? I'll add you to the gem, so that you can release it too.

**Comment by guitsaru** [comment]
Yeah, I came to the same conclusion on oEmbed.

I can do the `type` flag.

matt@guitsaru.com is my rubygems.org email.
