### ISSUE TITLE
Ping internet archive once a day with with new articles

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#451]
`curl -I "Accept: application/json" https://web.archive.org/save/{https://crimethinc.com/URL-TO-ADD} | grep Content-Location`

***

Should probably be a Heroku scheduled job thing + Rake task.

***

This and #262 will require some Heroku admin access. Lemme know when you get to that step and we can screen pair on my machine to set the right bits.

**Comment by just1602** [comment]
@veganstraightedge since you merged @explody PR, is there still something to do about this issue?

**Comment by veganstraightedge** [comment]
Yep! Good catch. Thanks @just1602.
