### ISSUE TITLE
Fix: Kramdown applying class to item after instead of before

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#463]
# Expected:

In Kramdown, this text should result in the h1 having a class of `darkred`. 

```markdown
# Say "No, you cannot come in. I do not consent to a search."
{: .darkred}

Keep the outer gate or door chain locked. If you must, step outside and close the door behind you. Better yet, speak through the door.
```

# Actual

The paragraph is getting a class of `darkred`

<img width="788" alt="screen shot 2017-08-31 at 12 41 51 pm" src="https://user-images.githubusercontent.com/4361/29942322-59a8f37a-8e4a-11e7-9a3f-916b7f9e7f1f.png">

**Comment by veganstraightedge** [comment]
See also: https://kramdown.gettalong.org/quickref.html#block-attributes

**Comment by explody** [comment]
Issue located, fix forthcoming

**Comment by veganstraightedge** [comment]
I think you should remove the `gsub` that's adding a `\n` in both the rails app and the `markdown_media` gem. If that double `\n` is important, we'll rediscover why.

:shipit:
