### ISSUE TITLE
Syndication: Twitter

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#47]
- Auto tweet link to article at publish time
- Smart truncation / elipsing
- Field in Article form for tweet preview with character count
- Ensure Twitter cards work with proper meta tags
- Consider @adactio's post: https://adactio.com/journal/9881
- [twitter tweet api doc ](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update)
- [twitter upload media api doc](https://developer.twitter.com/en/docs/media/upload-media/overview)
- Maybe use [this library](https://github.com/sferik/twitter)

**Comment by just1602** [comment]
We've been banned.
