### ISSUE TITLE
Create text only site

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#480]
In the style of these sites:

- http://thin.npr.org
- http://lite.cnn.io

Let's make a text only version of these pages:
- home page
- article page
- tag page
- category page
- paginated versions of each of those 

If someone other than me takes on this issue, let's talk strategy before diving in.

**Comment by TheConObs** [comment]
Have you taken this one on yet? Looks like it could be a fun one to pull off.

**Comment by veganstraightedge** [comment]
@jennifermf is working on it.

**Comment by socialecologist** [comment]
Initial considerations/questions:
- subdomain or separate folder?
- serve dynamically or generate static files, with a job?
- support/considerations for translations?
- re: tag page. Does this page currently exist? I could find /categories for that page?

**Comment by jmfcodes** [comment]
@socialecologist those are important considerations. i'm not sure how to address the first and third.

for the second... since text files are so small. i wondered if the text-only version could be generated automatically when the non-text version is created.

currently, each article on the main page has a `<style="background-image: url(https://cloudfront.crimethinc.com/assets/articles/2018/07/11/header.jpg)">` and i think for maximum accessibility, it would be good to include image alt-text. however, i don't think alt-text exists here on the main page.

**Comment by socialecologist** [comment]
Also need to figure out how to handle the routes. Right now the PR has `/txt` and `/txt/:article_id` for two of the pages.

**Comment by socialecologist** [comment]
re: background images. You'll see I'm just using a new layout for the text only pages, so those aren't showing up. Some of the articles however have html content format with `img` tags in the content, so those ones are showing up right now.

**Comment by socialecologist** [comment]
Yet another thing to consider is how to link to this from the main navigable piece of the website. Could add something to the main footer.

**Comment by veganstraightedge** [comment]
Hi @socialecologist. Thanks for getting into this.

Here's my opinion on what strategy would be best.

> subdomain or separate folder?

Subdomain. 

> serve dynamically or generate static files, with a job?

For now, dynamically like the image-full site. Generate static files is outside the scope of this issue. And if we did do that, it would also benefit doing it for the image-full site. It's not a slam dunk though. Re-generation / replacing old versions if they get updated, where to store them, where to serve them from, deployment process… all of these are trade-offs that come with moving to static site germination. So, for now, let's punt on this idea.

> support/considerations for translations

For now, we don't have translations. But they're _hopefully_ coming in the next couple months.

> Also need to figure out how to handle the routes. Right now the PR has /txt and /txt/:article_id for two of the pages.

This is the main reason that I'd like us to use a subdomain for this. Because it means all route Just Work™. 

Same for translations, when we implement them. However they're represented in the URL (or not) will get passed along all the same to the text only site.

> Yet another thing to consider is how to link to this from the main navigable piece of the website. Could add something to the main footer.

I think adding it to the footer is a good idea. Maybe under the site map section.


> re: background images. You'll see I'm just using a new layout for the text only pages, so those aren't showing up. Some of the articles however have html content format with img tags in the content, so those ones are showing up right now.

**Comment by veganstraightedge** [comment]
Here's my idea for how to handle linked css / style tags / background images. (More on images in article text later.)

If we put it at a subdomain, we can detect that subdomain in a Rack middleware (like the [www redirect middle ware](https://github.com/crimethinc/website/blob/master/app/middlewares/rack/apex_redirect.rb)), then we could set a bit in that request life cycle that says "hey, I'm in text only mode".

```ruby
# application_controller.rb
def text_only?
  # is some variable set by the middle ware because of the subdomain
end
helper_method :text_only?
```

Then that method could be used in views and controllers to conditionally show images and css.

```erb
<% unless text_only? %>
  <style …>
<% end %>
```

At that point, no need to create a new layout, etc. Just do/don't render images and css that are already there.

This approach will also make it easier to re-apply this strategy to the (_coming soon_) new site design.

**Comment by veganstraightedge** [comment]
Finally, how to deal with images in articles. This one is definitely the hardest!

For now, I think what we could do is if the request is in `text_only?` mode, run the rendered markdown through a method that uses nokogiri to find all img/video/audio tags and delete them from the out bound html before sending it to the browser.

In fact, all of them are wrapped up in `<figure>` tags. So, this method could target just that tag.

***

It would also be totally ok to punt this particular part of the "text only" site to a separate issue and build that after shipping the rest of this issue first. Your call.
