### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by biofilo** [crimethinc/website#485]
There is at least one broken link on the page:

https://crimethinc.com/2012/09/25/detailed-look-at-recipes-second-edition

https://crimethinc.com/podcast/24/transcript24.html

Here's another one: 

At https://crimethinc.com/2013/02/10/letter-to-the-egyptian-black-bloc this image is broken:

[https://crimethinc.com/blog/wp-content/uploads/2013/02/egyptletter2a.jpg id:arabic]

**Comment by just1602** [comment]
[First missing image](https://web.archive.org/web/20130325012631im_/http://cloudfront.crimethinc.com/blog/wp-content/uploads/2012/09/rfd-image-size-diagram-small.gif)
[Second missing image](https://web.archive.org/web/20130325020512im_/http://cloudfront.crimethinc.com/blog/wp-content/uploads/2012/09/rfd-page-size-diagram-small.gif)

**Comment by biofilo** [comment]
Thanks for finding those! It seems to me that there must have been "large" versions, since those are both marked "small" in the URLs...

**Comment by just1602** [comment]
I don't know. I find theme on the archived version on web.archive.org. They are the images use on the old wordpress version of the site.

**Comment by just1602** [comment]
@biofilo for the article "Letter to the egyptian black block" : change the image url from 
https://crimethinc.com/blog/wp-content/uploads/2013/02/egyptletter2a.jpg
to 
https://cloudfront.crimethinc.com/blog/wp-content/uploads/2013/02/egyptdownloadb.jpg

It'll work.

**Comment by biofilo** [comment]
@just1602 

J--I changed it, but whatever it is still isn't coming up.... now what?

Thanks!

**Comment by just1602** [comment]
It's weird, because when I modify it temporally with the firefox dev tools, it works. I don't know what to tell you. :/

![screenshot-2017-11-7 letter to the egyptian black bloc](https://user-images.githubusercontent.com/427123/32510933-4d335e0e-c3c0-11e7-92e6-739cb3caf657.png)

**Comment by biofilo** [comment]
Huh. Well, let's ask the others for help...? Surely we should be able to get the original and upload a new version or something?

**Comment by just1602** [comment]
The image is online. If you go to this [URL](https://cloudfront.crimethinc.com/blog/wp-content/uploads/2013/02/egyptdownloadb.jpg) you'll see the image. I just don't know why it don't change in the article. Maybe the caching as a bug.

@veganstraightedge any idea? :)

**Comment by veganstraightedge** [comment]
In https://crimethinc.com/2013/02/10/letter-to-the-egyptian-black-bloc:

I fixed this image by fixing this syntax. It needs two wrapping brackets, not just one. `[[ ]]` not `[ ]`.

`[https://crimethinc.com/blog/wp-content/uploads/2013/02/egyptletter2a.jpg id:arabic]`

=>

`[[https://crimethinc.com/blog/wp-content/uploads/2013/02/egyptletter2a.jpg id:arabic]]`

***

Working on the other image separately.

**Comment by veganstraightedge** [comment]
- [x] https://crimethinc.com/2012/09/25/detailed-look-at-recipes-second-edition

- [ ] https://crimethinc.com/podcast/24/transcript24.html

- [ ] https://crimethinc.com/2013/02/10/letter-to-the-egyptian-black-bloc

**Comment by veganstraightedge** [comment]
All fixed. Closing.

**Comment by biofilo** [comment]
Thanks y'all! Well done!
