### ISSUE TITLE
/vote is broken

### ISSUE THREAD

**Issue by benatcwc** [crimethinc/website#499]
Ben [9:40 AM] 
Apparently /vote is broken

Shane Becker [12:29 PM] 
what should `/vote` go to?

Ben [3:15 PM] 
it’s a redirect to http://www.crimethinc.com/tools/vote

Shane Becker [3:17 PM] 
what *should* it go to?

Ben [3:18 PM] 
It should go to /tools/vote, which is an article called Democracy is Bankrupt. Where’d it go?

Shane Becker [3:18 PM] 
tools/vote is not an article. tools/vote doesn’t exist.

[3:19] 
are you saying that you want `/vote` to redirect to some article called “Democracy is Bankrupt”?

Ben [3:19 PM] 
That’s where it went before the redesign broke /tools, so it seems like it should go there. Unless there’s somewhere better it should go…

Shane Becker [3:20 PM] 
so. what is the URL of that article that you want it to redirect to?

Ben [3:21 PM] 
lol, if i knew that i’d just make it so. but, as far as i know, the redesign broke /tools. i just found Democracy is Bankrupt through the Wayback Machine.

[3:21] 
http://web.archive.org/web/20120501102822/www.crimethinc.com/tools/vote

new messages
Shane Becker [3:22 PM] 
ok. will you create a github issue with all of this that you know about? and we’ll dig into it. please

**Comment by just1602** [comment]
Hello,

I try to grep the title or some setences in the seeds and i get nothing about this article. I try to find it with the website search bar and a found nothing too, so maybe the solution would be, after validation with the database content, to republish the article and assign it to the /vote url.

**Comment by veganstraightedge** [comment]
It looks like it didn't make it over in the site migration earlier this year. I'm manually adding it to the site now. Thanks for investigating this.

**Comment by veganstraightedge** [comment]
Fixed.

Added the article.

Redirected to https://crimethinc.com/2012/05/01/democracy-is-bankrupt-vote-here-stickers
