### ISSUE TITLE
[design] huge white space on the right side of the site

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#520]
There's a big white space we can scroll on the right side of the site.

<img width="1680" alt="screen shot 2017-11-10 at 7 59 16 pm" src="https://user-images.githubusercontent.com/427123/32684464-d56cb2c8-c651-11e7-9266-7f4332690a79.png">

**Comment by veganstraightedge** [comment]
How are you creating this situation? 

Is your browser window very large?
Is there whitespace on the left side too?
Can you screen shot your whole window?

**Comment by veganstraightedge** [comment]
@just1602 

How are you creating this situation?

Is your browser window very large?
Is there whitespace on the left side too?
Can you screen shot your whole window?

**Comment by just1602** [comment]
That's my whole window.
My browser window take all the space in my macbook pro 13'' screen.
There is only white space on the right. When I land on crimethinc, it's as usual, but I can scroll horizontally on the right.

**Comment by veganstraightedge** [comment]
Is it still happening? I just pushed a revert to production.

**Comment by just1602** [comment]
Didn't happening anymore !

Thx ! :)
