### ISSUE TITLE
Delete contributors/contributions

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#554]

**Comment by veganstraightedge** [comment]
@guitsaru I already did most of this on `drop_contributors` branch. I was unsure about how to remove it from the search view `.sql` file. Do I just delete those lines or does a new `.sql` file need to be created, ala a migration?

Would you mind finishing this issue?

- [ ] delete contributors and contributions from the .sql file

**Comment by guitsaru** [comment]
To share the knowledge about this, if you need to update it in the future:

https://github.com/thoughtbot/scenic#cool-but-what-if-i-need-to-change-that-view

`rails generate scenic:view search_results --materialized`

It'll copy the sql file to a v2 that you can edit.
