### ISSUE TITLE
Use TCE assets on CDN

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#584]
I'm trying to clean house on `/public` as much as possible. To that end, and related to #575, Try to see if everything Just Works™ with TCE assets from the CDN.

- [ ] https://cloudfront.crimethinc.com/assets/tce/css
- [ ] https://cloudfront.crimethinc.com/assets/tce/js
- [ ] https://cloudfront.crimethinc.com/assets/tce/css/tcefont
- [ ] https://cloudfront.crimethinc.com/assets/tce/images

Also, because of historical CDN organizational reasons, can you:

- [ ] Use https://cloudfront.crimethinc.com/assets/tce instead of https://cloudfront.crimethinc.com/tce/

**Comment by astronaut-wannabe** [comment]
#595 closes this **sort of**. 

only TCEs that use the erb template will no longer depend on the old assets. The remaining static html TCEs still rely on the original asset paths. 

**so we cannot delete the assets from /public just yet )**

**Comment by veganstraightedge** [comment]
Copy that. I will not delete anything from `/public` in app or in `/tce` in S3 until all of the static files are migrated to the erb template and yaml translation. 👍🏻
