### ISSUE TITLE
Update form_ tags to Rails 5 style

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#600]
Rails 5.1 introduced `form_with` to put both `form_tag` and `form_for` in the same abstraction. Let's update all of our forms to use the `form_with` style.

While this is being one, let's change all forms to use `form` instead of `f`.

- [ ] search forms
- [ ] admin forms
- [ ] `|f|` => `|form|`
- [ ] `f.` => `form.`

**Comment by TheConObs** [comment]
Anyone tackling this one?

**Comment by veganstraightedge** [comment]
@TheConObs  I don't think so. It's all yours!

**Comment by TheConObs** [comment]
Awesome.

**Comment by just1602** [comment]
Since the @TheConObs PR has been merge I'll close this one.
