### ISSUE TITLE
TCE Farsi tweaks

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#609]
- [x] vertical space need between "to change everything" main heading and navbar https://github.com/crimethinc/website/pull/651
- [x] all titles on images need a shadow. either black text / white shadow or white text / black shadow. - fixed: https://github.com/crimethinc/website/pull/614
- [x] there's a grey stripe above the image of image of the cocktail thrower - fixed: https://github.com/crimethinc/website/pull/612
- [x] "the secret is to begin" text is way to big for its box - fixed: https://github.com/crimethinc/website/pull/612
- [x] all of the titles on images could use some vertical space at the top
- [x] all of the body copy might be too small (because of font differences between farsi and latin), try embiggening by a couple points - fixed: https://github.com/crimethinc/website/pull/614
- [ ] ~translate meta tags~ *deferred*
- [x] figure out what font the PDF uses and match (seems like it's easier for a screen) - fixed: https://github.com/crimethinc/website/pull/612
- [ ] ~translate image `alt=""` tags~ *deferred*
- [ ] ~line breaks in the titles~ *deferred*
- [ ] ~ltr the header~ *deferred*
- [ ] ~maybe rtl the images (images on right, text on left)~ *deferred*

**Comment by astronaut-wannabe** [comment]
Also some stuff I think needs done:
- translate meta tags
- figure out what font the PDF uses and match (seems like it's easier for a
screen)
- translate image all alt tags
- line breaks in the titles
- ltr the header
- maybe ltr the images (images on right, text on left)

>

**Comment by veganstraightedge** [comment]
Good ideas. 👍🏻

**Comment by astronaut-wannabe** [comment]
Almost positive this is the font: https://www.google.com/get/noto/#kufi-arab

**Comment by veganstraightedge** [comment]
Seems good to me. :shipit:
