### ISSUE TITLE
Change auth/identity to protect anonymity

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#61]
- make email an optional field
  - not the user id for signin/up
- add username
  - use it for signin/up
- add name
  - use it for display on article bylines
- add added_by (points to a user_id)
- create Vouch model
  - vouched_for (points to a user_id)
  - vouched_by (points to a user_id)

**Comment by greggawatt** [comment]
Did you build the auth from scratch? I'm not seeing any reference to a gem in the gemfile.

**Comment by veganstraightedge** [comment]
Yeah. I rolled it from scratch using `has_secure_password` and `bcrypt`.

Based on the Rails Cast episode on auth.

**Comment by greggawatt** [comment]
cool, I'd be willing to take this on and decoupling usernames from emails. 
Is the user functionality only intended for authors or would public users be making accounts as well? Do we need password retrieval functionality?

**Comment by veganstraightedge** [comment]
Frankly, this issue has a fair deal of uncertainty around it. So, I don't want to stop you from tackling a thing that you want to do. But at the same time, I feel like this needs more definition. Is there anything else that you'd like to do in the meantime?

**Comment by greggawatt** [comment]
Fair enough! I'll look at some more issues tomorrow and see.

Thanks!!
