### ISSUE TITLE
Structure the logs

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#627]
https://twitter.com/mipsytipsy/status/951272678345687040

https://honeycomb.io/blog/2017/04/lies-my-parents-told-me-about-logs

**Comment by just1602** [comment]
What do we really want to do with that? 

I check about log structuration and the thing that come back the most is [The elastic suite](https://www.elastic.co/fr/products), which is `logstach + elasticsearch + kibana`. It read and parse your log files to json and send them to elasticserach, then kabina (the analytics dashboard) query the logs you've send to elasticsearch to render charts with your data.

My questions : 

* Do we really want to install such a huge stack
* Do we really need all these features ?
* Can we write our own and simpler stack for this kind of work?

The good point is that we could use that to check the number of view of a n article or a page without having an update query on every request, but we could also do it in javascript / ajax to avoid the update query.

**Comment by veganstraightedge** [comment]
Will you also investigate what Heroku add-ons there are that might help us with this kind of thing please?

**Comment by just1602** [comment]
There is the [logging section](https://elements.heroku.com/addons/#logging), there is [elasticsearch](https://elements.heroku.com/addons/foundelasticsearch) if we want to implement the elastic suite presented above and there is the [Metrics and Analitics](https://elements.heroku.com/addons/) add-ons.

**Comment by veganstraightedge** [comment]
More reading about observability: 

- https://medium.com/@adron/reading-up-on-observability-and-monitoring-efee79bd291d
- https://honeycomb.io/blog/2017/10/metrics-not-the-observability-droids-youre-looking-for
- https://honeycomb.io/blog/2017/08/observability-whats-in-a-name

**Comment by vvallee** [comment]
My 2c on ELK. Amazing platform if you can afford the hardware required. The free version does not have RBAC or user logins, but is regardless extremely powerful. 

What is your ingest rate and document size?

**Comment by vvallee** [comment]
Would love to chat sometime if you'd care to invite me to slack?
