### ISSUE TITLE
chromedriver no longer part of brew repo

### ISSUE THREAD

**Issue by vvallee** [crimethinc/website#724]
==> Installing Homebrew dependencies...
Using postgresql
Using heroku
Error: No available formula with the name "chromedriver"

The fix appears to be installing it via cask.

After tapping caskroom/cask by using brew tap caskroom/cask, install chromedriver using brew cask install chromedriver

**Comment by astronaut-wannabe** [comment]
hmm, I think I switched travis CI and local-dev to use firefox instead of chrome in PR https://github.com/crimethinc/website/pull/632

I think the chrome tests still run in heroku, but are not installed via homebrew.

so maybe it is okay to just remove `chromedriver` from `Brewfile`?

**Comment by vvallee** [comment]
As a sidenote the setup script still fails after installing chromedriver via cask.

**Comment by veganstraightedge** [comment]
@vvallee I've invited you to this GH org. Care to PR removing `chromedriver` from `Brewfile`?

And will you make a separate issue for `script/setup` failing please? With they output of your failure and a description of your environment. Thanks.
