### ISSUE TITLE
Download vimeo videos?

### ISSUE THREAD

**Issue by ralphtheninja** [crimethinc/website#757]
It would be really nice if you could download the movies in the video section, like you can with the podcasts.

EDIT: Just noticed that you _can_ download using `youtube-dl`, which is awesome if you have that tool and know how to use it. But for non technical users it would be nice with a download button.

**Comment by veganstraightedge** [comment]
https://github.com/crimethinc/website/commit/9295223573e7962d2fbccc04c8e41a9f30d00f1d 


<img width="716" alt="screen shot 2018-10-20 at 11 00 25 pm" src="https://user-images.githubusercontent.com/4361/47263725-1e2ce900-d4bc-11e8-9fde-ddd7a3af0fb3.png">
