### ISSUE TITLE
Missing mobile header image?

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#758]
https://crimethinc.com/2016/09/28/feature-the-secret-is-to-begin-getting-started-further-resources-frequently-asked-questions

On mobile, the header / hero image is missing or doesn't load. Since the background and heading text are both white, it can't be read.

**Comment by astronaut-wannabe** [comment]
the image url that is not loading: https://crimethinc.com/tce/images/takeflight-phone@2x.jpg

this one is similar in name, but loads. Not sure if it is the same image: 


https://cloudfront.crimethinc.com/assets/tce/images/takeflight-phonesmall@2x.jpg

**Comment by veganstraightedge** [comment]
Thanks @astronaut-wannabe!

I uploaded that file to the /begin directory on S3.

https://cloudfront.crimethinc.com/assets/features/begin/images/takeflight-small.jpg

I updated the CSS that refers to it. It's wait for the Cloudfront cache to reset on it.

https://cloudfront.crimethinc.com/assets/features/begin/custom.css
