### ISSUE TITLE
Let's encrypt certificate for tochangeeverything.com

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#770]
`https://tochangeeverything.com` has a self signed ssl certificate which is invalid. It'd be nice to have a valid SSL certificate even if it's a domain that is only use to redirect to `cwc.im/tce` it's steal pretty clean and used by the social media team. :)

**Comment by just1602** [comment]
We still have to generate a SSL certificate for the domain and make it point to `https://crimethinc.com`.

**Comment by veganstraightedge** [comment]
https://crimethinc.com/tce

Works now. 👍🏻
