### ISSUE TITLE
problem in <figcaption> tag

### ISSUE THREAD

**Issue by reedjones** [crimethinc/website#814]
The article on this page [here](https://crimethinc.com/2018/08/02/taking-stock-of-the-nicaraguan-uprising-asking-the-hard-questions-after-three-months-of-revolt)

There is a figcaption tag that starts with a closing tag 

```
</figcaption>   <-- should be <figcaption>
  </figcaption>
```

Edited: 
sorry it was figcaption not figure
anyway problem is fixed now

**Comment by just1602** [comment]
If you check the code just above, you'll see the opening `figcaption` tag :

```
<figure class="">
<img src="https://cloudfront.crimethinc.com/assets/articles/2018/08/02/4.jpg" />   <figcaption> <!-- HERE -->
    <p>“Surrender? Your mama!”</p>
  </figcaption>
</figure>
```
