### ISSUE TITLE
Remove image/audio/video tags in Lite Mode™

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#913]
When `img`/`audio`/`video` tags are in the HTML, even if they are hidden by CSS, they still get downloaded by the browser.

So… we need to not render those tags before serving the HTML response back to the browser. I see a few options the seem feasible (there may be others):

1. In the parsing code that sends found instances of `[[ ]]` blobs to the MarkdownMedia, check if we're in `lite_mode?`. If so, don't send to MarkdownMedia. If not, proceed normally.

2. Use Nokogiri to look for `figure`, `img`, `audio`, and `video` tags the render HTML from `render_markdown` and then delete them from the HTML before sending the response back to the browser.

3. Push it upstream to the MarkdownMedia gem (https://github.com/veganstraightedge/markdown_media), adding a new optional argument that says "hey don't render this to an embed, just give me back what I sent you, as a clickable link to that URL" (Eg, `[[ http://example.com/video.mp4 A righteous caption! ]]` => `<figure><a href="http://example.com/video.mp4">example.com/video.mp4</a><figcaption>A righteous caption!</figcaption></figure>`

***

My hunch is leaning toward `#3` because the end user still gets the most amount of content (and thus context) and something actionable (ie, click this link to get to the image/audio/video if they want it) and can still read the captions.

Thoughts?

**Comment by GeoffFoley** [comment]
I agree. I think #3 gives the most bang for the buck as it could be used for instances, where desired, outside of just lite_mode.

**Comment by veganstraightedge** [comment]
#3 was done in MarkdownMedia.

https://github.com/veganstraightedge/markdown_media/commit/33b632fd67a10fdb6ff4a0b0e1aaa2eebcfd0660
