### ISSUE TITLE
Add switcher between Lite Mode™ and Classic Mode™

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#915]
We need a switch between `lite.crimethinc.com` and `crimethinc.com` and back again.

I'm thinking it should be:

- [x] in the footer on the classic site and
- [x] in the header for the of the lite site.

- [x] It should take you to the page that you're currently on, but in the other mode

`crimethinc.com/about` => `lite.crimethinc.com/about`,

**NOT**

`crimethinc.com/about` => `lite.crimethinc.com`

**Comment by GeoffFoley** [comment]
![image](https://user-images.githubusercontent.com/36054273/48962435-dd6f3680-ef77-11e8-9857-29233afa192f.png)

**Comment by GeoffFoley** [comment]
Made the name a little larger, as well.
