### ISSUE TITLE
Don't make OS specific calls in script/setup

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#928]
I was reviewing the #927 PR and I realize there is a call to brew in the `setup` script. Since the `bootstrap` script is OSX specific, it could be nice to avoid os specific call in the `setup` script and start postgresql in the `boostrap` script instead of the `setup` one.

**Comment by veganstraightedge** [comment]
https://github.com/crimethinc/website/blob/master/script/setup#L18

`script/setup` first calls `script/bootstrap`, so moving it wouldn't make the script anymore Linux friendly. For bettor and for worse, the scripts are really meant for folx doing development on macOS.

I'm open to a curated set of scripts for Linux folx, if you'd want to do that. I know nothing about Linux development, so I don't know what that would look like.

**Comment by just1602** [comment]
Ok,

I personally don't use the bootstrap / setup scripts, so I'll check if there's folx doing dev on linux and who think that some linux scripts could be usefull.
