### ISSUE TITLE
Completely redesign Steal From Work Day mini-site

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#931]
https://stealfromwork.crimethinc.com

Depends on https://github.com/crimethinc/website/issues/930

**Comment by just1602** [comment]
Do we want a specific design for stealfromwork even if it's a path and not a independent site with its own domain?

If we still want a different design, to wee want to simply use a static site generator and buy `stealfromwork.com` or something like that or we move it in the main crimethinc app and there is a way to have a different design for this part of the site.. Or we just don't care about the design ! :P
