### ISSUE TITLE
Move from sass-rails to sassc-rails

### ISSUE THREAD

**Issue by just1602** [crimethinc/website#952]
Since this [issue](https://github.com/sass/sassc-ruby/pull/85) have been closed we can move to `sassc-rails`.

**Comment by veganstraightedge** [comment]
Already have 😉

https://github.com/crimethinc/website/blob/master/Gemfile#L19

**Comment by just1602** [comment]
Euum, that's weird, I receive de warning to change when I ran `bundle install` on my install.. :P
