### ISSUE TITLE
Tags/Categories in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#963]
Don't render images in Lite Mode.

# Examples

https://lite.crimethinc.com/categories/arts
https://lite.crimethinc.com/tags/anarchy

# TODO

- [ ] `categories#show` article header images
- [ ] `tags#show` article header images

**Comment by GeoffFoley** [comment]
![Categories](https://user-images.githubusercontent.com/36054273/54093644-3a400280-4357-11e9-9787-e5c52e995928.jpg)

![Tags](https://user-images.githubusercontent.com/36054273/54093646-3e6c2000-4357-11e9-87bd-83f4ae49b1e1.jpg)
