### ISSUE TITLE
Zines in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#966]
Don't render images in Lite Mode.

# Examples

https://lite.crimethinc.com/zines
https://lite.crimethinc.com/zines/to-change-everything

# TODO

- [ ] zines cover images

**Comment by GeoffFoley** [comment]
![Zines](https://user-images.githubusercontent.com/36054273/54093568-67d87c00-4356-11e9-94f1-71652d9ed628.jpg)

![Zines2](https://user-images.githubusercontent.com/36054273/54093570-6d35c680-4356-11e9-89dc-916957ff9ecc.jpg)
