### ISSUE TITLE
Journals in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#967]
Don't render images in Lite Mode.

# Examples

https://lite.crimethinc.com/journals
https://lite.crimethinc.com/journals/rolling-thunder-12-spring-2015

## TODO

- [ ] cover images
- [ ] gallery images

**Comment by GeoffFoley** [comment]
![Journals](https://user-images.githubusercontent.com/36054273/54093525-f7c9f600-4355-11e9-98b7-b9c25796b84c.jpg)

![RollingThunder12](https://user-images.githubusercontent.com/36054273/54093532-02848b00-4356-11e9-837d-ade8b71e02b1.jpg)
