### ISSUE TITLE
Posters in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#968]
Don't render images in Lite Mode.

# Examples

https://lite.crimethinc.com/posters
https://lite.crimethinc.com/posters/borders-the-global-caste-system

## TODO

- [ ] cover images
- [ ] gallery images

**Comment by GeoffFoley** [comment]
![posters](https://user-images.githubusercontent.com/36054273/54093469-6e1a2880-4355-11e9-97c6-c3b01af65f9f.jpg)

![BlocktheWall](https://user-images.githubusercontent.com/36054273/54093472-75d9cd00-4355-11e9-94ef-4051b405863a.jpg)
