### ISSUE TITLE
Stickers in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#969]
Don't render images in Lite Mode.

# Examples

https://lite.crimethinc.com/stickers
https://lite.crimethinc.com/stickers/immigrants-welcome

## TODO

- [ ] cover images
- [ ] gallery images

**Comment by GeoffFoley** [comment]
![Stickers](https://user-images.githubusercontent.com/36054273/54093382-bc7af780-4354-11e9-8900-26775a1e062f.jpg)

![ImmigrantsWelcome](https://user-images.githubusercontent.com/36054273/54093385-c13fab80-4354-11e9-8ae1-a5d5417c52ad.jpg)
