### ISSUE TITLE
Logos in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#970]
Don't render images in Lite Mode.

# Examples

https://lite.crimethinc.com/logos
https://lite.crimethinc.com/logos/boat

## TODO

- [x] cover images
- [x] gallery images

**Comment by GeoffFoley** [comment]
![Boat](https://user-images.githubusercontent.com/36054273/54093327-e8e24400-4353-11e9-9562-6b933c49cfd9.jpg)
![Logos](https://user-images.githubusercontent.com/36054273/54093328-ec75cb00-4353-11e9-8f46-526decf1711f.jpg)
